// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ccl.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CmteLink struct {
	CandID               string   `protobuf:"bytes,1,opt,name=CandID,proto3" json:"CandID,omitempty"`
	ElectnYr             int32    `protobuf:"varint,2,opt,name=ElectnYr,proto3" json:"ElectnYr,omitempty"`
	CmteID               string   `protobuf:"bytes,3,opt,name=CmteID,proto3" json:"CmteID,omitempty"`
	CmteType             string   `protobuf:"bytes,4,opt,name=CmteType,proto3" json:"CmteType,omitempty"`
	CmteDsgn             string   `protobuf:"bytes,5,opt,name=CmteDsgn,proto3" json:"CmteDsgn,omitempty"`
	LinkID               string   `protobuf:"bytes,6,opt,name=LinkID,proto3" json:"LinkID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmteLink) Reset()         { *m = CmteLink{} }
func (m *CmteLink) String() string { return proto.CompactTextString(m) }
func (*CmteLink) ProtoMessage()    {}
func (*CmteLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_40d7f298a154d826, []int{0}
}

func (m *CmteLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmteLink.Unmarshal(m, b)
}
func (m *CmteLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmteLink.Marshal(b, m, deterministic)
}
func (m *CmteLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmteLink.Merge(m, src)
}
func (m *CmteLink) XXX_Size() int {
	return xxx_messageInfo_CmteLink.Size(m)
}
func (m *CmteLink) XXX_DiscardUnknown() {
	xxx_messageInfo_CmteLink.DiscardUnknown(m)
}

var xxx_messageInfo_CmteLink proto.InternalMessageInfo

func (m *CmteLink) GetCandID() string {
	if m != nil {
		return m.CandID
	}
	return ""
}

func (m *CmteLink) GetElectnYr() int32 {
	if m != nil {
		return m.ElectnYr
	}
	return 0
}

func (m *CmteLink) GetCmteID() string {
	if m != nil {
		return m.CmteID
	}
	return ""
}

func (m *CmteLink) GetCmteType() string {
	if m != nil {
		return m.CmteType
	}
	return ""
}

func (m *CmteLink) GetCmteDsgn() string {
	if m != nil {
		return m.CmteDsgn
	}
	return ""
}

func (m *CmteLink) GetLinkID() string {
	if m != nil {
		return m.LinkID
	}
	return ""
}

func init() {
	proto.RegisterType((*CmteLink)(nil), "protobuf.CmteLink")
}

func init() { proto.RegisterFile("ccl.proto", fileDescriptor_40d7f298a154d826) }

var fileDescriptor_40d7f298a154d826 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x4e, 0xce, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0xcb, 0x18, 0xb9,
	0x38, 0x9c, 0x73, 0x4b, 0x52, 0x7d, 0x32, 0xf3, 0xb2, 0x85, 0xc4, 0xb8, 0xd8, 0x9c, 0x13, 0xf3,
	0x52, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x21, 0x29, 0x2e, 0x0e,
	0xd7, 0x9c, 0xd4, 0xe4, 0x92, 0xbc, 0xc8, 0x22, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x38,
	0x1f, 0xac, 0x27, 0xb7, 0x24, 0xd5, 0xd3, 0x45, 0x82, 0x19, 0xaa, 0x07, 0xcc, 0x03, 0xe9, 0x01,
	0xb1, 0x42, 0x2a, 0x0b, 0x52, 0x25, 0x58, 0xc0, 0x32, 0x70, 0x3e, 0x4c, 0xce, 0xa5, 0x38, 0x3d,
	0x4f, 0x82, 0x15, 0x21, 0x07, 0xe2, 0x83, 0xcc, 0x03, 0xb9, 0xc5, 0xd3, 0x45, 0x82, 0x0d, 0x62,
	0x1e, 0x84, 0x97, 0xc4, 0x06, 0x76, 0xb2, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xc5, 0xae,
	0x36, 0xc6, 0x00, 0x00, 0x00,
}
