// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmpn_fin.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CmpnFinancials struct {
	CandID               string               `protobuf:"bytes,1,opt,name=CandID,proto3" json:"CandID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	PartyCd              string               `protobuf:"bytes,3,opt,name=PartyCd,proto3" json:"PartyCd,omitempty"`
	Party                string               `protobuf:"bytes,4,opt,name=Party,proto3" json:"Party,omitempty"`
	TotalReceipts        float32              `protobuf:"fixed32,5,opt,name=TotalReceipts,proto3" json:"TotalReceipts,omitempty"`
	TransFrAuth          float32              `protobuf:"fixed32,6,opt,name=TransFrAuth,proto3" json:"TransFrAuth,omitempty"`
	TotalDisbsmts        float32              `protobuf:"fixed32,7,opt,name=TotalDisbsmts,proto3" json:"TotalDisbsmts,omitempty"`
	TransToAuth          float32              `protobuf:"fixed32,8,opt,name=TransToAuth,proto3" json:"TransToAuth,omitempty"`
	COHBOP               float32              `protobuf:"fixed32,9,opt,name=COHBOP,proto3" json:"COHBOP,omitempty"`
	COHCOP               float32              `protobuf:"fixed32,10,opt,name=COHCOP,proto3" json:"COHCOP,omitempty"`
	CandConts            float32              `protobuf:"fixed32,11,opt,name=CandConts,proto3" json:"CandConts,omitempty"`
	CandLoans            float32              `protobuf:"fixed32,12,opt,name=CandLoans,proto3" json:"CandLoans,omitempty"`
	OtherLoans           float32              `protobuf:"fixed32,13,opt,name=OtherLoans,proto3" json:"OtherLoans,omitempty"`
	CandLoanRepay        float32              `protobuf:"fixed32,14,opt,name=CandLoanRepay,proto3" json:"CandLoanRepay,omitempty"`
	OtherLoanRepay       float32              `protobuf:"fixed32,15,opt,name=OtherLoanRepay,proto3" json:"OtherLoanRepay,omitempty"`
	DebtsOwedBy          float32              `protobuf:"fixed32,16,opt,name=DebtsOwedBy,proto3" json:"DebtsOwedBy,omitempty"`
	TotalIndvConts       float32              `protobuf:"fixed32,17,opt,name=TotalIndvConts,proto3" json:"TotalIndvConts,omitempty"`
	OfficeState          string               `protobuf:"bytes,18,opt,name=OfficeState,proto3" json:"OfficeState,omitempty"`
	OfficeDistrict       string               `protobuf:"bytes,19,opt,name=OfficeDistrict,proto3" json:"OfficeDistrict,omitempty"`
	SpecElection         string               `protobuf:"bytes,20,opt,name=SpecElection,proto3" json:"SpecElection,omitempty"`
	PrimElection         string               `protobuf:"bytes,21,opt,name=PrimElection,proto3" json:"PrimElection,omitempty"`
	RunElection          string               `protobuf:"bytes,22,opt,name=RunElection,proto3" json:"RunElection,omitempty"`
	GenElection          string               `protobuf:"bytes,23,opt,name=GenElection,proto3" json:"GenElection,omitempty"`
	GenElectionPct       float32              `protobuf:"fixed32,24,opt,name=GenElectionPct,proto3" json:"GenElectionPct,omitempty"`
	OtherCmteConts       float32              `protobuf:"fixed32,25,opt,name=OtherCmteConts,proto3" json:"OtherCmteConts,omitempty"`
	PtyConts             float32              `protobuf:"fixed32,26,opt,name=PtyConts,proto3" json:"PtyConts,omitempty"`
	CvgEndDate           *timestamp.Timestamp `protobuf:"bytes,27,opt,name=CvgEndDate,proto3" json:"CvgEndDate,omitempty"`
	IndvRefunds          float32              `protobuf:"fixed32,28,opt,name=IndvRefunds,proto3" json:"IndvRefunds,omitempty"`
	CmteRefunds          float32              `protobuf:"fixed32,29,opt,name=CmteRefunds,proto3" json:"CmteRefunds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CmpnFinancials) Reset()         { *m = CmpnFinancials{} }
func (m *CmpnFinancials) String() string { return proto.CompactTextString(m) }
func (*CmpnFinancials) ProtoMessage()    {}
func (*CmpnFinancials) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae11dfa2f8fc908c, []int{0}
}

func (m *CmpnFinancials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmpnFinancials.Unmarshal(m, b)
}
func (m *CmpnFinancials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmpnFinancials.Marshal(b, m, deterministic)
}
func (m *CmpnFinancials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmpnFinancials.Merge(m, src)
}
func (m *CmpnFinancials) XXX_Size() int {
	return xxx_messageInfo_CmpnFinancials.Size(m)
}
func (m *CmpnFinancials) XXX_DiscardUnknown() {
	xxx_messageInfo_CmpnFinancials.DiscardUnknown(m)
}

var xxx_messageInfo_CmpnFinancials proto.InternalMessageInfo

func (m *CmpnFinancials) GetCandID() string {
	if m != nil {
		return m.CandID
	}
	return ""
}

func (m *CmpnFinancials) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CmpnFinancials) GetPartyCd() string {
	if m != nil {
		return m.PartyCd
	}
	return ""
}

func (m *CmpnFinancials) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *CmpnFinancials) GetTotalReceipts() float32 {
	if m != nil {
		return m.TotalReceipts
	}
	return 0
}

func (m *CmpnFinancials) GetTransFrAuth() float32 {
	if m != nil {
		return m.TransFrAuth
	}
	return 0
}

func (m *CmpnFinancials) GetTotalDisbsmts() float32 {
	if m != nil {
		return m.TotalDisbsmts
	}
	return 0
}

func (m *CmpnFinancials) GetTransToAuth() float32 {
	if m != nil {
		return m.TransToAuth
	}
	return 0
}

func (m *CmpnFinancials) GetCOHBOP() float32 {
	if m != nil {
		return m.COHBOP
	}
	return 0
}

func (m *CmpnFinancials) GetCOHCOP() float32 {
	if m != nil {
		return m.COHCOP
	}
	return 0
}

func (m *CmpnFinancials) GetCandConts() float32 {
	if m != nil {
		return m.CandConts
	}
	return 0
}

func (m *CmpnFinancials) GetCandLoans() float32 {
	if m != nil {
		return m.CandLoans
	}
	return 0
}

func (m *CmpnFinancials) GetOtherLoans() float32 {
	if m != nil {
		return m.OtherLoans
	}
	return 0
}

func (m *CmpnFinancials) GetCandLoanRepay() float32 {
	if m != nil {
		return m.CandLoanRepay
	}
	return 0
}

func (m *CmpnFinancials) GetOtherLoanRepay() float32 {
	if m != nil {
		return m.OtherLoanRepay
	}
	return 0
}

func (m *CmpnFinancials) GetDebtsOwedBy() float32 {
	if m != nil {
		return m.DebtsOwedBy
	}
	return 0
}

func (m *CmpnFinancials) GetTotalIndvConts() float32 {
	if m != nil {
		return m.TotalIndvConts
	}
	return 0
}

func (m *CmpnFinancials) GetOfficeState() string {
	if m != nil {
		return m.OfficeState
	}
	return ""
}

func (m *CmpnFinancials) GetOfficeDistrict() string {
	if m != nil {
		return m.OfficeDistrict
	}
	return ""
}

func (m *CmpnFinancials) GetSpecElection() string {
	if m != nil {
		return m.SpecElection
	}
	return ""
}

func (m *CmpnFinancials) GetPrimElection() string {
	if m != nil {
		return m.PrimElection
	}
	return ""
}

func (m *CmpnFinancials) GetRunElection() string {
	if m != nil {
		return m.RunElection
	}
	return ""
}

func (m *CmpnFinancials) GetGenElection() string {
	if m != nil {
		return m.GenElection
	}
	return ""
}

func (m *CmpnFinancials) GetGenElectionPct() float32 {
	if m != nil {
		return m.GenElectionPct
	}
	return 0
}

func (m *CmpnFinancials) GetOtherCmteConts() float32 {
	if m != nil {
		return m.OtherCmteConts
	}
	return 0
}

func (m *CmpnFinancials) GetPtyConts() float32 {
	if m != nil {
		return m.PtyConts
	}
	return 0
}

func (m *CmpnFinancials) GetCvgEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.CvgEndDate
	}
	return nil
}

func (m *CmpnFinancials) GetIndvRefunds() float32 {
	if m != nil {
		return m.IndvRefunds
	}
	return 0
}

func (m *CmpnFinancials) GetCmteRefunds() float32 {
	if m != nil {
		return m.CmteRefunds
	}
	return 0
}

func init() {
	proto.RegisterType((*CmpnFinancials)(nil), "protobuf.CmpnFinancials")
}

func init() { proto.RegisterFile("cmpn_fin.proto", fileDescriptor_ae11dfa2f8fc908c) }

var fileDescriptor_ae11dfa2f8fc908c = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x93, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x80, 0xd5, 0xb1, 0xad, 0xad, 0xbb, 0x15, 0x30, 0x63, 0x1c, 0x65, 0x40, 0x35, 0x21, 0xd4,
	0xa7, 0x4e, 0x82, 0x37, 0xde, 0x58, 0xb2, 0xc1, 0x24, 0x44, 0xa2, 0xac, 0xef, 0xc8, 0x4d, 0x9c,
	0xce, 0x52, 0xe3, 0x44, 0xf1, 0x75, 0xa8, 0x7f, 0x97, 0x5f, 0x82, 0x7c, 0x6e, 0x52, 0x67, 0x4f,
	0xf5, 0x7d, 0xf7, 0xf5, 0x72, 0x77, 0x96, 0xd9, 0x38, 0x2d, 0x2a, 0xfd, 0x27, 0x57, 0x7a, 0x5e,
	0xd5, 0x25, 0x96, 0x7c, 0x40, 0x3f, 0xcb, 0x4d, 0x3e, 0xf9, 0xb8, 0x2a, 0xcb, 0xd5, 0x5a, 0x5e,
	0x35, 0xe0, 0x0a, 0x55, 0x21, 0x0d, 0x8a, 0xa2, 0x72, 0xea, 0xe5, 0xbf, 0x3e, 0x1b, 0x07, 0x45,
	0xa5, 0x6f, 0x95, 0x16, 0x3a, 0x55, 0x62, 0x6d, 0xf8, 0x39, 0x3b, 0x0e, 0x84, 0xce, 0xee, 0x42,
	0xe8, 0x4d, 0x7b, 0xb3, 0x61, 0xb2, 0x8b, 0x38, 0x67, 0x87, 0xbf, 0x45, 0x21, 0xe1, 0x80, 0x28,
	0x9d, 0x39, 0xb0, 0x7e, 0x2c, 0x6a, 0xdc, 0x06, 0x19, 0x3c, 0x23, 0xdc, 0x84, 0xfc, 0x8c, 0x1d,
	0xd1, 0x11, 0x0e, 0x89, 0xbb, 0x80, 0x7f, 0x62, 0xa7, 0x8b, 0x12, 0xc5, 0x3a, 0x91, 0xa9, 0x54,
	0x15, 0x1a, 0x38, 0x9a, 0xf6, 0x66, 0x07, 0x49, 0x17, 0xf2, 0x29, 0x1b, 0x2d, 0x6a, 0xa1, 0xcd,
	0x6d, 0xfd, 0x7d, 0x83, 0x0f, 0x70, 0x4c, 0x8e, 0x8f, 0xda, 0x3a, 0xa1, 0x32, 0x4b, 0x53, 0xa0,
	0x81, 0xbe, 0x57, 0xa7, 0x81, 0x6d, 0x9d, 0x45, 0x49, 0x75, 0x06, 0x5e, 0x1d, 0x87, 0x68, 0xd6,
	0xe8, 0xe7, 0x75, 0x14, 0xc3, 0x90, 0x92, 0xbb, 0x68, 0xc7, 0x83, 0x28, 0x06, 0xd6, 0xf2, 0x20,
	0x8a, 0xf9, 0x05, 0x1b, 0xda, 0x6d, 0x04, 0xa5, 0x46, 0x03, 0x23, 0x4a, 0xed, 0x41, 0x93, 0xfd,
	0x55, 0x0a, 0x6d, 0xe0, 0x64, 0x9f, 0x25, 0xc0, 0x3f, 0x30, 0x16, 0xe1, 0x83, 0xac, 0x5d, 0xfa,
	0x94, 0xd2, 0x1e, 0xb1, 0x33, 0x35, 0x72, 0x22, 0x2b, 0xb1, 0x85, 0xb1, 0x9b, 0xa9, 0x03, 0xf9,
	0x67, 0x36, 0x6e, 0xff, 0xe3, 0xb4, 0xe7, 0xa4, 0x3d, 0xa1, 0x76, 0xf6, 0x50, 0x2e, 0xd1, 0x44,
	0x7f, 0x65, 0x76, 0xbd, 0x85, 0x17, 0x6e, 0x76, 0x0f, 0xd9, 0x4a, 0xb4, 0xae, 0x3b, 0x9d, 0x3d,
	0xba, 0x81, 0x5e, 0xba, 0x4a, 0x5d, 0x6a, 0x2b, 0x45, 0x79, 0xae, 0x52, 0x79, 0x8f, 0x02, 0x25,
	0x70, 0xba, 0x4f, 0x1f, 0x51, 0x4f, 0x14, 0x86, 0xca, 0x60, 0xad, 0x52, 0x84, 0x57, 0x24, 0x3d,
	0xa1, 0xfc, 0x92, 0x9d, 0xdc, 0x57, 0x32, 0xbd, 0x59, 0xcb, 0x14, 0x55, 0xa9, 0xe1, 0x8c, 0xac,
	0x0e, 0xb3, 0x4e, 0x5c, 0xab, 0xa2, 0x75, 0x5e, 0x3b, 0xc7, 0x67, 0xb6, 0xa3, 0x64, 0xa3, 0x5b,
	0xe5, 0xdc, 0x75, 0xe4, 0x21, 0x6b, 0xfc, 0x90, 0x7b, 0xe3, 0x8d, 0x33, 0x3c, 0x64, 0x7b, 0xf6,
	0xc2, 0x38, 0x45, 0x00, 0x37, 0x7d, 0x97, 0xb6, 0xfb, 0x0e, 0x0a, 0x94, 0x6e, 0x4b, 0x6f, 0xbd,
	0x7d, 0xb7, 0x94, 0x4f, 0xd8, 0x20, 0xc6, 0xad, 0x33, 0x26, 0x64, 0xb4, 0x31, 0xff, 0xc6, 0x58,
	0xf0, 0xb8, 0xba, 0xd1, 0x59, 0x68, 0x17, 0xf8, 0x6e, 0xda, 0x9b, 0x8d, 0xbe, 0x4c, 0xe6, 0xee,
	0x69, 0xce, 0x9b, 0xa7, 0x39, 0x5f, 0x34, 0x4f, 0x33, 0xf1, 0x6c, 0x3b, 0x89, 0xbd, 0x8a, 0x44,
	0xe6, 0x1b, 0x9d, 0x19, 0xb8, 0x70, 0xf7, 0xe8, 0x21, 0x6b, 0xd8, 0x36, 0x1a, 0xe3, 0xbd, 0x33,
	0x3c, 0xb4, 0x3c, 0xa6, 0x6f, 0x7c, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x98, 0x1c, 0xf8, 0x1d,
	0x28, 0x04, 0x00, 0x00,
}
