// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmte_fin.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CmteFinancials struct {
	CmteID               string               `protobuf:"bytes,1,opt,name=CmteID,proto3" json:"CmteID,omitempty"`
	TotalReceipts        float32              `protobuf:"fixed32,2,opt,name=TotalReceipts,proto3" json:"TotalReceipts,omitempty"`
	TxsFromAff           float32              `protobuf:"fixed32,3,opt,name=TxsFromAff,proto3" json:"TxsFromAff,omitempty"`
	IndvConts            float32              `protobuf:"fixed32,4,opt,name=IndvConts,proto3" json:"IndvConts,omitempty"`
	OtherConts           float32              `protobuf:"fixed32,5,opt,name=OtherConts,proto3" json:"OtherConts,omitempty"`
	CandCont             float32              `protobuf:"fixed32,6,opt,name=CandCont,proto3" json:"CandCont,omitempty"`
	CandLoans            float32              `protobuf:"fixed32,7,opt,name=CandLoans,proto3" json:"CandLoans,omitempty"`
	TotalLoans           float32              `protobuf:"fixed32,8,opt,name=TotalLoans,proto3" json:"TotalLoans,omitempty"`
	TotalDisb            float32              `protobuf:"fixed32,9,opt,name=TotalDisb,proto3" json:"TotalDisb,omitempty"`
	TxToAff              float32              `protobuf:"fixed32,10,opt,name=TxToAff,proto3" json:"TxToAff,omitempty"`
	IndvRefunds          float32              `protobuf:"fixed32,11,opt,name=IndvRefunds,proto3" json:"IndvRefunds,omitempty"`
	OtherRefunds         float32              `protobuf:"fixed32,12,opt,name=OtherRefunds,proto3" json:"OtherRefunds,omitempty"`
	LoanRepay            float32              `protobuf:"fixed32,13,opt,name=LoanRepay,proto3" json:"LoanRepay,omitempty"`
	CashBOP              float32              `protobuf:"fixed32,14,opt,name=CashBOP,proto3" json:"CashBOP,omitempty"`
	CashCOP              float32              `protobuf:"fixed32,15,opt,name=CashCOP,proto3" json:"CashCOP,omitempty"`
	DebtsOwed            float32              `protobuf:"fixed32,16,opt,name=DebtsOwed,proto3" json:"DebtsOwed,omitempty"`
	NonFedTxsRecvd       float32              `protobuf:"fixed32,17,opt,name=NonFedTxsRecvd,proto3" json:"NonFedTxsRecvd,omitempty"`
	ContToOtherCmte      float32              `protobuf:"fixed32,18,opt,name=ContToOtherCmte,proto3" json:"ContToOtherCmte,omitempty"`
	IndExp               float32              `protobuf:"fixed32,19,opt,name=IndExp,proto3" json:"IndExp,omitempty"`
	PartyExp             float32              `protobuf:"fixed32,20,opt,name=PartyExp,proto3" json:"PartyExp,omitempty"`
	NonFedSharedExp      float32              `protobuf:"fixed32,21,opt,name=NonFedSharedExp,proto3" json:"NonFedSharedExp,omitempty"`
	CovgEndDate          *timestamp.Timestamp `protobuf:"bytes,22,opt,name=CovgEndDate,proto3" json:"CovgEndDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CmteFinancials) Reset()         { *m = CmteFinancials{} }
func (m *CmteFinancials) String() string { return proto.CompactTextString(m) }
func (*CmteFinancials) ProtoMessage()    {}
func (*CmteFinancials) Descriptor() ([]byte, []int) {
	return fileDescriptor_911a89ef744e9e4a, []int{0}
}

func (m *CmteFinancials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmteFinancials.Unmarshal(m, b)
}
func (m *CmteFinancials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmteFinancials.Marshal(b, m, deterministic)
}
func (m *CmteFinancials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmteFinancials.Merge(m, src)
}
func (m *CmteFinancials) XXX_Size() int {
	return xxx_messageInfo_CmteFinancials.Size(m)
}
func (m *CmteFinancials) XXX_DiscardUnknown() {
	xxx_messageInfo_CmteFinancials.DiscardUnknown(m)
}

var xxx_messageInfo_CmteFinancials proto.InternalMessageInfo

func (m *CmteFinancials) GetCmteID() string {
	if m != nil {
		return m.CmteID
	}
	return ""
}

func (m *CmteFinancials) GetTotalReceipts() float32 {
	if m != nil {
		return m.TotalReceipts
	}
	return 0
}

func (m *CmteFinancials) GetTxsFromAff() float32 {
	if m != nil {
		return m.TxsFromAff
	}
	return 0
}

func (m *CmteFinancials) GetIndvConts() float32 {
	if m != nil {
		return m.IndvConts
	}
	return 0
}

func (m *CmteFinancials) GetOtherConts() float32 {
	if m != nil {
		return m.OtherConts
	}
	return 0
}

func (m *CmteFinancials) GetCandCont() float32 {
	if m != nil {
		return m.CandCont
	}
	return 0
}

func (m *CmteFinancials) GetCandLoans() float32 {
	if m != nil {
		return m.CandLoans
	}
	return 0
}

func (m *CmteFinancials) GetTotalLoans() float32 {
	if m != nil {
		return m.TotalLoans
	}
	return 0
}

func (m *CmteFinancials) GetTotalDisb() float32 {
	if m != nil {
		return m.TotalDisb
	}
	return 0
}

func (m *CmteFinancials) GetTxToAff() float32 {
	if m != nil {
		return m.TxToAff
	}
	return 0
}

func (m *CmteFinancials) GetIndvRefunds() float32 {
	if m != nil {
		return m.IndvRefunds
	}
	return 0
}

func (m *CmteFinancials) GetOtherRefunds() float32 {
	if m != nil {
		return m.OtherRefunds
	}
	return 0
}

func (m *CmteFinancials) GetLoanRepay() float32 {
	if m != nil {
		return m.LoanRepay
	}
	return 0
}

func (m *CmteFinancials) GetCashBOP() float32 {
	if m != nil {
		return m.CashBOP
	}
	return 0
}

func (m *CmteFinancials) GetCashCOP() float32 {
	if m != nil {
		return m.CashCOP
	}
	return 0
}

func (m *CmteFinancials) GetDebtsOwed() float32 {
	if m != nil {
		return m.DebtsOwed
	}
	return 0
}

func (m *CmteFinancials) GetNonFedTxsRecvd() float32 {
	if m != nil {
		return m.NonFedTxsRecvd
	}
	return 0
}

func (m *CmteFinancials) GetContToOtherCmte() float32 {
	if m != nil {
		return m.ContToOtherCmte
	}
	return 0
}

func (m *CmteFinancials) GetIndExp() float32 {
	if m != nil {
		return m.IndExp
	}
	return 0
}

func (m *CmteFinancials) GetPartyExp() float32 {
	if m != nil {
		return m.PartyExp
	}
	return 0
}

func (m *CmteFinancials) GetNonFedSharedExp() float32 {
	if m != nil {
		return m.NonFedSharedExp
	}
	return 0
}

func (m *CmteFinancials) GetCovgEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.CovgEndDate
	}
	return nil
}

func init() {
	proto.RegisterType((*CmteFinancials)(nil), "protobuf.CmteFinancials")
}

func init() { proto.RegisterFile("cmte_fin.proto", fileDescriptor_911a89ef744e9e4a) }

var fileDescriptor_911a89ef744e9e4a = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x5f, 0x6f, 0xd3, 0x30,
	0x14, 0xc5, 0xd5, 0xc1, 0xba, 0xd6, 0xdd, 0x3a, 0x30, 0x30, 0x5d, 0x55, 0x08, 0xaa, 0x09, 0xa1,
	0x3e, 0x75, 0x12, 0xbc, 0xf2, 0x02, 0xe9, 0x2a, 0x55, 0x42, 0xa4, 0x0a, 0x79, 0x47, 0x4e, 0x7c,
	0xd3, 0x46, 0x6a, 0xec, 0x28, 0xf6, 0x4a, 0xf6, 0x75, 0xf9, 0x24, 0xe8, 0xda, 0x49, 0xfa, 0xe7,
	0xa9, 0x3d, 0xbf, 0x73, 0xee, 0x1f, 0xc7, 0x66, 0xe3, 0xb4, 0xb0, 0xf8, 0x27, 0xcb, 0xd5, 0xbc,
	0xac, 0xb4, 0xd5, 0x7c, 0xe0, 0x7e, 0x92, 0xa7, 0x6c, 0xf2, 0x71, 0xa3, 0xf5, 0x66, 0x87, 0x0f,
	0x2d, 0x78, 0xb0, 0x79, 0x81, 0xc6, 0x8a, 0xa2, 0xf4, 0xd1, 0xfb, 0x7f, 0x97, 0x6c, 0x1c, 0x14,
	0x16, 0x97, 0xb9, 0x12, 0x2a, 0xcd, 0xc5, 0xce, 0xf0, 0x3b, 0xd6, 0x27, 0xb2, 0x5a, 0x40, 0x6f,
	0xda, 0x9b, 0x0d, 0xa3, 0x46, 0xf1, 0x4f, 0xec, 0x26, 0xd6, 0x56, 0xec, 0x22, 0x4c, 0x31, 0x2f,
	0xad, 0x81, 0x8b, 0x69, 0x6f, 0x76, 0x11, 0x9d, 0x42, 0xfe, 0x81, 0xb1, 0xb8, 0x36, 0xcb, 0x4a,
	0x17, 0xdf, 0xb3, 0x0c, 0x5e, 0xb8, 0xc8, 0x11, 0xe1, 0xef, 0xd9, 0x70, 0xa5, 0xe4, 0x3e, 0xd0,
	0xca, 0x1a, 0x78, 0xe9, 0xec, 0x03, 0xa0, 0xea, 0xd0, 0x6e, 0xb1, 0xf2, 0xf6, 0xa5, 0xaf, 0x3e,
	0x10, 0x3e, 0x61, 0x83, 0x40, 0x28, 0x49, 0x02, 0xfa, 0xce, 0xed, 0x34, 0x75, 0xa6, 0xff, 0x3f,
	0xb5, 0x50, 0x06, 0xae, 0x7c, 0xe7, 0x0e, 0xb8, 0xbd, 0x68, 0x51, 0x6f, 0x0f, 0x9a, 0xbd, 0x3a,
	0x42, 0xd5, 0x4e, 0x2d, 0x72, 0x93, 0xc0, 0xd0, 0x57, 0x77, 0x80, 0x03, 0xbb, 0x8a, 0xeb, 0x58,
	0xd3, 0x91, 0x98, 0xf3, 0x5a, 0xc9, 0xa7, 0x6c, 0x44, 0xeb, 0x47, 0x98, 0x3d, 0x29, 0x69, 0x60,
	0xe4, 0xdc, 0x63, 0xc4, 0xef, 0xd9, 0xb5, 0x3b, 0x41, 0x1b, 0xb9, 0x76, 0x91, 0x13, 0x46, 0xd3,
	0x69, 0x8d, 0x08, 0x4b, 0xf1, 0x0c, 0x37, 0x7e, 0x7a, 0x07, 0x68, 0x7a, 0x20, 0xcc, 0xf6, 0x47,
	0xb8, 0x86, 0xb1, 0x9f, 0xde, 0xc8, 0xd6, 0x09, 0xc2, 0x35, 0xdc, 0x1e, 0x9c, 0x20, 0x5c, 0x53,
	0xc7, 0x05, 0x26, 0xd6, 0x84, 0x7f, 0x51, 0xc2, 0x2b, 0xdf, 0xb1, 0x03, 0xfc, 0x33, 0x1b, 0xff,
	0xd2, 0x6a, 0x89, 0x32, 0xae, 0x4d, 0x84, 0xe9, 0x5e, 0xc2, 0x6b, 0x17, 0x39, 0xa3, 0x7c, 0xc6,
	0x6e, 0xe9, 0xdb, 0xc6, 0xda, 0xdf, 0x41, 0x61, 0x11, 0xb8, 0x0b, 0x9e, 0x63, 0x7a, 0x35, 0x2b,
	0x25, 0x1f, 0xeb, 0x12, 0xde, 0xb8, 0x40, 0xa3, 0xe8, 0xc6, 0xd6, 0xa2, 0xb2, 0xcf, 0xe4, 0xbc,
	0xf5, 0x37, 0xd6, 0x6a, 0xea, 0xee, 0xe7, 0xfd, 0xde, 0x8a, 0x0a, 0x5d, 0xf1, 0x3b, 0xdf, 0xfd,
	0x0c, 0xf3, 0x6f, 0x6c, 0x14, 0xe8, 0xfd, 0xe6, 0x51, 0xc9, 0x85, 0xb0, 0x08, 0x77, 0xd3, 0xde,
	0x6c, 0xf4, 0x65, 0x32, 0xf7, 0xaf, 0x7b, 0xde, 0xbe, 0xee, 0x79, 0xdc, 0xbe, 0xee, 0xe8, 0x38,
	0x9e, 0xf4, 0x5d, 0xe0, 0xeb, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x0e, 0xf9, 0x7e, 0x28,
	0x03, 0x00, 0x00,
}
