// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchResult struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`
	Employer             string   `protobuf:"bytes,5,opt,name=Employer,proto3" json:"Employer,omitempty"`
	Bucket               string   `protobuf:"bytes,6,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Years                []string `protobuf:"bytes,7,rep,name=Years,proto3" json:"Years,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResult) Reset()         { *m = SearchResult{} }
func (m *SearchResult) String() string { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()    {}
func (*SearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{0}
}

func (m *SearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResult.Unmarshal(m, b)
}
func (m *SearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResult.Marshal(b, m, deterministic)
}
func (m *SearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResult.Merge(m, src)
}
func (m *SearchResult) XXX_Size() int {
	return xxx_messageInfo_SearchResult.Size(m)
}
func (m *SearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResult proto.InternalMessageInfo

func (m *SearchResult) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SearchResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchResult) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SearchResult) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SearchResult) GetEmployer() string {
	if m != nil {
		return m.Employer
	}
	return ""
}

func (m *SearchResult) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *SearchResult) GetYears() []string {
	if m != nil {
		return m.Years
	}
	return nil
}

type ResultList struct {
	IDs                  []string `protobuf:"bytes,1,rep,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultList) Reset()         { *m = ResultList{} }
func (m *ResultList) String() string { return proto.CompactTextString(m) }
func (*ResultList) ProtoMessage()    {}
func (*ResultList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{1}
}

func (m *ResultList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultList.Unmarshal(m, b)
}
func (m *ResultList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultList.Marshal(b, m, deterministic)
}
func (m *ResultList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultList.Merge(m, src)
}
func (m *ResultList) XXX_Size() int {
	return xxx_messageInfo_ResultList.Size(m)
}
func (m *ResultList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultList.DiscardUnknown(m)
}

var xxx_messageInfo_ResultList proto.InternalMessageInfo

func (m *ResultList) GetIDs() []string {
	if m != nil {
		return m.IDs
	}
	return nil
}

type LookupMap struct {
	Lookup               map[string]*SearchResult `protobuf:"bytes,1,rep,name=Lookup,proto3" json:"Lookup,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *LookupMap) Reset()         { *m = LookupMap{} }
func (m *LookupMap) String() string { return proto.CompactTextString(m) }
func (*LookupMap) ProtoMessage()    {}
func (*LookupMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{2}
}

func (m *LookupMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupMap.Unmarshal(m, b)
}
func (m *LookupMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupMap.Marshal(b, m, deterministic)
}
func (m *LookupMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupMap.Merge(m, src)
}
func (m *LookupMap) XXX_Size() int {
	return xxx_messageInfo_LookupMap.Size(m)
}
func (m *LookupMap) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupMap.DiscardUnknown(m)
}

var xxx_messageInfo_LookupMap proto.InternalMessageInfo

func (m *LookupMap) GetLookup() map[string]*SearchResult {
	if m != nil {
		return m.Lookup
	}
	return nil
}

type IndexData struct {
	TermsSize            float32              `protobuf:"fixed32,1,opt,name=TermsSize,proto3" json:"TermsSize,omitempty"`
	LookupSize           float32              `protobuf:"fixed32,2,opt,name=LookupSize,proto3" json:"LookupSize,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=LastUpdated,proto3" json:"LastUpdated,omitempty"`
	Completed            map[string]bool      `protobuf:"bytes,4,rep,name=Completed,proto3" json:"Completed,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Shards               map[string]float32   `protobuf:"bytes,5,rep,name=Shards,proto3" json:"Shards,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	YearsCompleted       []string             `protobuf:"bytes,6,rep,name=YearsCompleted,proto3" json:"YearsCompleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *IndexData) Reset()         { *m = IndexData{} }
func (m *IndexData) String() string { return proto.CompactTextString(m) }
func (*IndexData) ProtoMessage()    {}
func (*IndexData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{3}
}

func (m *IndexData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexData.Unmarshal(m, b)
}
func (m *IndexData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexData.Marshal(b, m, deterministic)
}
func (m *IndexData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexData.Merge(m, src)
}
func (m *IndexData) XXX_Size() int {
	return xxx_messageInfo_IndexData.Size(m)
}
func (m *IndexData) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexData.DiscardUnknown(m)
}

var xxx_messageInfo_IndexData proto.InternalMessageInfo

func (m *IndexData) GetTermsSize() float32 {
	if m != nil {
		return m.TermsSize
	}
	return 0
}

func (m *IndexData) GetLookupSize() float32 {
	if m != nil {
		return m.LookupSize
	}
	return 0
}

func (m *IndexData) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func (m *IndexData) GetCompleted() map[string]bool {
	if m != nil {
		return m.Completed
	}
	return nil
}

func (m *IndexData) GetShards() map[string]float32 {
	if m != nil {
		return m.Shards
	}
	return nil
}

func (m *IndexData) GetYearsCompleted() []string {
	if m != nil {
		return m.YearsCompleted
	}
	return nil
}

type PartitionMap struct {
	Partitions           map[string]bool `protobuf:"bytes,1,rep,name=Partitions,proto3" json:"Partitions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PartitionMap) Reset()         { *m = PartitionMap{} }
func (m *PartitionMap) String() string { return proto.CompactTextString(m) }
func (*PartitionMap) ProtoMessage()    {}
func (*PartitionMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{4}
}

func (m *PartitionMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionMap.Unmarshal(m, b)
}
func (m *PartitionMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionMap.Marshal(b, m, deterministic)
}
func (m *PartitionMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionMap.Merge(m, src)
}
func (m *PartitionMap) XXX_Size() int {
	return xxx_messageInfo_PartitionMap.Size(m)
}
func (m *PartitionMap) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionMap.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionMap proto.InternalMessageInfo

func (m *PartitionMap) GetPartitions() map[string]bool {
	if m != nil {
		return m.Partitions
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchResult)(nil), "protobuf.SearchResult")
	proto.RegisterType((*ResultList)(nil), "protobuf.ResultList")
	proto.RegisterType((*LookupMap)(nil), "protobuf.LookupMap")
	proto.RegisterMapType((map[string]*SearchResult)(nil), "protobuf.LookupMap.LookupEntry")
	proto.RegisterType((*IndexData)(nil), "protobuf.IndexData")
	proto.RegisterMapType((map[string]bool)(nil), "protobuf.IndexData.CompletedEntry")
	proto.RegisterMapType((map[string]float32)(nil), "protobuf.IndexData.ShardsEntry")
	proto.RegisterType((*PartitionMap)(nil), "protobuf.PartitionMap")
	proto.RegisterMapType((map[string]bool)(nil), "protobuf.PartitionMap.PartitionsEntry")
}

func init() { proto.RegisterFile("index.proto", fileDescriptor_f750e0f7889345b5) }

var fileDescriptor_f750e0f7889345b5 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x25, 0x69, 0x1b, 0x9b, 0x9b, 0xa5, 0xca, 0xb0, 0x2c, 0x43, 0x90, 0xdd, 0x25, 0x0f, 0x8b,
	0x0f, 0x92, 0x85, 0xfa, 0xe0, 0x07, 0x2b, 0x88, 0xdb, 0x15, 0x0a, 0x55, 0x34, 0x5d, 0x1f, 0x7c,
	0x9c, 0xdd, 0x8e, 0xdb, 0xd0, 0xa4, 0x13, 0x32, 0x13, 0x31, 0xfe, 0x0f, 0xf1, 0x07, 0x08, 0xfe,
	0x4e, 0x99, 0x3b, 0x69, 0x66, 0x2c, 0x82, 0xf8, 0x94, 0x7b, 0xce, 0x3d, 0x77, 0xee, 0xcc, 0x39,
	0x81, 0x28, 0xdf, 0xae, 0xf8, 0xd7, 0xb4, 0xaa, 0x85, 0x12, 0x64, 0x8c, 0x9f, 0x9b, 0xe6, 0x73,
	0x7c, 0x72, 0x27, 0xc4, 0x5d, 0xc1, 0xcf, 0x77, 0xc4, 0xb9, 0xca, 0x4b, 0x2e, 0x15, 0x2b, 0x2b,
	0x23, 0x4d, 0x7e, 0x79, 0x70, 0xb0, 0xe4, 0xac, 0xbe, 0x5d, 0x67, 0x5c, 0x36, 0x85, 0x22, 0x13,
	0xf0, 0xe7, 0x33, 0xea, 0x9d, 0x7a, 0x8f, 0xc2, 0xcc, 0x9f, 0xcf, 0x08, 0x81, 0xe1, 0x3b, 0x56,
	0x72, 0xea, 0x23, 0x83, 0xb5, 0xe6, 0x2e, 0x73, 0xd5, 0xd2, 0x81, 0xe1, 0x74, 0x4d, 0x0e, 0x61,
	0xb4, 0x54, 0x4c, 0x71, 0x3a, 0x44, 0xd2, 0x00, 0x12, 0xc3, 0xf8, 0xaa, 0xac, 0x0a, 0xd1, 0xf2,
	0x9a, 0x8e, 0xb0, 0xd1, 0x63, 0x72, 0x04, 0xc1, 0xeb, 0xe6, 0x76, 0xc3, 0x15, 0x0d, 0xb0, 0xd3,
	0x21, 0x7d, 0xd2, 0x27, 0xce, 0x6a, 0x49, 0xef, 0x9d, 0x0e, 0xf4, 0x49, 0x08, 0x92, 0x63, 0x00,
	0x73, 0xc3, 0x45, 0x2e, 0x15, 0x79, 0x00, 0x83, 0xf9, 0x4c, 0x52, 0x0f, 0x15, 0xba, 0x4c, 0x7e,
	0x78, 0x10, 0x2e, 0x84, 0xd8, 0x34, 0xd5, 0x5b, 0x56, 0x91, 0xa7, 0x10, 0x18, 0x80, 0x92, 0x68,
	0x7a, 0x92, 0xee, 0x1c, 0x48, 0x7b, 0x51, 0x57, 0x5d, 0x6d, 0x55, 0xdd, 0x66, 0x9d, 0x3c, 0xfe,
	0x00, 0x91, 0x43, 0xeb, 0x3d, 0x1b, 0xde, 0x76, 0x76, 0xe8, 0x92, 0x3c, 0x86, 0xd1, 0x17, 0x56,
	0x34, 0xc6, 0x90, 0x68, 0x7a, 0x64, 0x0f, 0x76, 0x6d, 0xcc, 0x8c, 0xe8, 0x85, 0xff, 0xcc, 0x4b,
	0x7e, 0x0e, 0x20, 0x9c, 0xeb, 0x74, 0x66, 0x4c, 0x31, 0xf2, 0x10, 0xc2, 0x6b, 0x5e, 0x97, 0x72,
	0x99, 0x7f, 0xe3, 0x78, 0xae, 0x9f, 0x59, 0x82, 0x1c, 0x03, 0x98, 0xf5, 0xd8, 0xf6, 0xb1, 0xed,
	0x30, 0xe4, 0x02, 0xa2, 0x05, 0x93, 0xea, 0x63, 0xb5, 0x62, 0x8a, 0xaf, 0x30, 0x80, 0x68, 0x1a,
	0xa7, 0x26, 0x65, 0x7b, 0x95, 0xeb, 0x5d, 0xca, 0x99, 0x2b, 0x27, 0xaf, 0x20, 0xbc, 0x14, 0x65,
	0x55, 0x70, 0x3d, 0x3b, 0x44, 0x63, 0x12, 0x3b, 0xd4, 0xdf, 0x31, 0xed, 0x45, 0xc6, 0x1b, 0x3b,
	0xa4, 0x7d, 0x5d, 0xae, 0x59, 0xbd, 0x92, 0x74, 0xb4, 0xef, 0xab, 0x1d, 0x37, 0x8a, 0xce, 0x57,
	0x03, 0xc8, 0x19, 0x4c, 0x30, 0x47, 0xbb, 0x3f, 0xc0, 0xec, 0xf6, 0xd8, 0xf8, 0x02, 0x26, 0x7f,
	0x6e, 0xff, 0x4b, 0x04, 0x87, 0x6e, 0x04, 0x63, 0xc7, 0xea, 0xf8, 0x39, 0x44, 0xce, 0xf2, 0x7f,
	0x8d, 0xfa, 0x6e, 0x4a, 0xdf, 0x3d, 0x38, 0x78, 0xcf, 0x6a, 0x95, 0xab, 0x5c, 0x6c, 0xf5, 0x2f,
	0xf4, 0x06, 0xa0, 0xc7, 0xb2, 0xfb, 0x8d, 0xce, 0xec, 0x73, 0x5d, 0xad, 0x05, 0xdd, 0xab, 0x9d,
	0xc9, 0xf8, 0x25, 0xdc, 0xdf, 0x6b, 0xff, 0xcf, 0x93, 0x6e, 0x02, 0xdc, 0xf8, 0xe4, 0x77, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x06, 0x11, 0x76, 0xe2, 0xe1, 0x03, 0x00, 0x00,
}
