// Code generated by protoc-gen-go. DO NOT EDIT.
// source: org.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Organization struct {
	ID                   string             `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	City                 string             `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	State                string             `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`
	Zip                  string             `protobuf:"bytes,5,opt,name=Zip,proto3" json:"Zip,omitempty"`
	Occupation           string             `protobuf:"bytes,6,opt,name=Occupation,proto3" json:"Occupation,omitempty"`
	Employer             string             `protobuf:"bytes,7,opt,name=Employer,proto3" json:"Employer,omitempty"`
	Transactions         []string           `protobuf:"bytes,8,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	TotalOutAmt          float32            `protobuf:"fixed32,9,opt,name=TotalOutAmt,proto3" json:"TotalOutAmt,omitempty"`
	TotalOutTxs          float32            `protobuf:"fixed32,10,opt,name=TotalOutTxs,proto3" json:"TotalOutTxs,omitempty"`
	AvgTxOut             float32            `protobuf:"fixed32,11,opt,name=AvgTxOut,proto3" json:"AvgTxOut,omitempty"`
	TotalInAmt           float32            `protobuf:"fixed32,12,opt,name=TotalInAmt,proto3" json:"TotalInAmt,omitempty"`
	TotalInTxs           float32            `protobuf:"fixed32,13,opt,name=TotalInTxs,proto3" json:"TotalInTxs,omitempty"`
	AvgTxIn              float32            `protobuf:"fixed32,14,opt,name=AvgTxIn,proto3" json:"AvgTxIn,omitempty"`
	NetBalance           float32            `protobuf:"fixed32,15,opt,name=NetBalance,proto3" json:"NetBalance,omitempty"`
	RecipientsAmt        map[string]float32 `protobuf:"bytes,16,rep,name=RecipientsAmt,proto3" json:"RecipientsAmt,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	RecipientsTxs        map[string]float32 `protobuf:"bytes,17,rep,name=RecipientsTxs,proto3" json:"RecipientsTxs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	SendersAmt           map[string]float32 `protobuf:"bytes,18,rep,name=SendersAmt,proto3" json:"SendersAmt,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	SendersTxs           map[string]float32 `protobuf:"bytes,19,rep,name=SendersTxs,proto3" json:"SendersTxs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccb462779e28924f, []int{0}
}

func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Organization) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Organization) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Organization) GetOccupation() string {
	if m != nil {
		return m.Occupation
	}
	return ""
}

func (m *Organization) GetEmployer() string {
	if m != nil {
		return m.Employer
	}
	return ""
}

func (m *Organization) GetTransactions() []string {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Organization) GetTotalOutAmt() float32 {
	if m != nil {
		return m.TotalOutAmt
	}
	return 0
}

func (m *Organization) GetTotalOutTxs() float32 {
	if m != nil {
		return m.TotalOutTxs
	}
	return 0
}

func (m *Organization) GetAvgTxOut() float32 {
	if m != nil {
		return m.AvgTxOut
	}
	return 0
}

func (m *Organization) GetTotalInAmt() float32 {
	if m != nil {
		return m.TotalInAmt
	}
	return 0
}

func (m *Organization) GetTotalInTxs() float32 {
	if m != nil {
		return m.TotalInTxs
	}
	return 0
}

func (m *Organization) GetAvgTxIn() float32 {
	if m != nil {
		return m.AvgTxIn
	}
	return 0
}

func (m *Organization) GetNetBalance() float32 {
	if m != nil {
		return m.NetBalance
	}
	return 0
}

func (m *Organization) GetRecipientsAmt() map[string]float32 {
	if m != nil {
		return m.RecipientsAmt
	}
	return nil
}

func (m *Organization) GetRecipientsTxs() map[string]float32 {
	if m != nil {
		return m.RecipientsTxs
	}
	return nil
}

func (m *Organization) GetSendersAmt() map[string]float32 {
	if m != nil {
		return m.SendersAmt
	}
	return nil
}

func (m *Organization) GetSendersTxs() map[string]float32 {
	if m != nil {
		return m.SendersTxs
	}
	return nil
}

func init() {
	proto.RegisterType((*Organization)(nil), "protobuf.Organization")
	proto.RegisterMapType((map[string]float32)(nil), "protobuf.Organization.RecipientsAmtEntry")
	proto.RegisterMapType((map[string]float32)(nil), "protobuf.Organization.RecipientsTxsEntry")
	proto.RegisterMapType((map[string]float32)(nil), "protobuf.Organization.SendersAmtEntry")
	proto.RegisterMapType((map[string]float32)(nil), "protobuf.Organization.SendersTxsEntry")
}

func init() { proto.RegisterFile("org.proto", fileDescriptor_ccb462779e28924f) }

var fileDescriptor_ccb462779e28924f = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0xaf, 0x93, 0x40,
	0x10, 0xc7, 0x03, 0xbc, 0xf7, 0x5a, 0xa6, 0x7d, 0x3f, 0x5c, 0x3d, 0x6c, 0xde, 0xc1, 0x90, 0x77,
	0x30, 0x78, 0xe1, 0xa0, 0x17, 0x63, 0x62, 0x62, 0xb5, 0x35, 0xe1, 0x52, 0x12, 0xca, 0xc9, 0xdb,
	0x16, 0xd7, 0x86, 0x48, 0x17, 0x02, 0x4b, 0x03, 0xfe, 0xad, 0xfe, 0x31, 0x66, 0x06, 0xdb, 0x2e,
	0x36, 0x26, 0xb5, 0x27, 0x66, 0xbe, 0xdf, 0x99, 0xcf, 0x0c, 0x30, 0xe0, 0x16, 0xd5, 0x26, 0x28,
	0xab, 0x42, 0x17, 0x6c, 0x4c, 0x8f, 0x75, 0xf3, 0xfd, 0xe9, 0xd7, 0x08, 0xa6, 0x51, 0xb5, 0x11,
	0x2a, 0xfb, 0x29, 0x74, 0x56, 0x28, 0x76, 0x07, 0x76, 0x38, 0xe7, 0x96, 0x67, 0xf9, 0x6e, 0x6c,
	0x87, 0x73, 0xc6, 0xe0, 0x6a, 0x29, 0xb6, 0x92, 0xdb, 0xa4, 0x50, 0x8c, 0xda, 0xe7, 0x4c, 0x77,
	0xdc, 0xe9, 0x35, 0x8c, 0xd9, 0x0b, 0xb8, 0x5e, 0x69, 0xa1, 0x25, 0xbf, 0x22, 0xb1, 0x4f, 0xd8,
	0x03, 0x38, 0x5f, 0xb3, 0x92, 0x5f, 0x93, 0x86, 0x21, 0x7b, 0x09, 0x10, 0xa5, 0x69, 0x53, 0xd2,
	0x34, 0x7e, 0x43, 0x86, 0xa1, 0xb0, 0x47, 0x18, 0x2f, 0xb6, 0x65, 0x5e, 0x74, 0xb2, 0xe2, 0x23,
	0x72, 0x0f, 0x39, 0x7b, 0x82, 0x69, 0x52, 0x09, 0x55, 0x8b, 0x14, 0x4b, 0x6b, 0x3e, 0xf6, 0x1c,
	0xdf, 0x8d, 0x07, 0x1a, 0xf3, 0x60, 0x92, 0x14, 0x5a, 0xe4, 0x51, 0xa3, 0x67, 0x5b, 0xcd, 0x5d,
	0xcf, 0xf2, 0xed, 0xd8, 0x94, 0xcc, 0x8a, 0xa4, 0xad, 0x39, 0x0c, 0x2b, 0x92, 0xb6, 0xc6, 0x1d,
	0x66, 0xbb, 0x4d, 0xd2, 0x46, 0x8d, 0xe6, 0x13, 0xb2, 0x0f, 0x39, 0xee, 0x4f, 0xa5, 0xa1, 0x42,
	0xfc, 0x94, 0x5c, 0x43, 0x31, 0x7c, 0x84, 0xdf, 0x0e, 0x7c, 0x64, 0x73, 0x18, 0x11, 0x2b, 0x54,
	0xfc, 0x8e, 0xcc, 0x7d, 0x8a, 0x9d, 0x4b, 0xa9, 0x3f, 0x89, 0x5c, 0xa8, 0x54, 0xf2, 0xfb, 0xbe,
	0xf3, 0xa8, 0xb0, 0x08, 0x6e, 0x63, 0x99, 0x66, 0x65, 0x26, 0x95, 0xae, 0x71, 0xf8, 0x83, 0xe7,
	0xf8, 0x93, 0x37, 0xaf, 0x83, 0xfd, 0xcf, 0x0c, 0xcc, 0x1f, 0x19, 0x0c, 0x6a, 0x17, 0x4a, 0x57,
	0x5d, 0x3c, 0xec, 0x1f, 0x02, 0x71, 0xdb, 0x67, 0x67, 0x02, 0x93, 0xb6, 0x3e, 0x01, 0xe2, 0xbb,
	0x7d, 0x01, 0x58, 0x49, 0xf5, 0x4d, 0x56, 0xb4, 0x1e, 0x23, 0xda, 0xab, 0x7f, 0xd0, 0x8e, 0x85,
	0x3d, 0xca, 0xe8, 0x34, 0x38, 0xb8, 0xd5, 0xf3, 0x73, 0x38, 0x87, 0x95, 0x8c, 0xce, 0xc7, 0x8f,
	0xc0, 0x4e, 0xbf, 0x02, 0xde, 0xe4, 0x0f, 0xd9, 0xfd, 0x39, 0x71, 0x0c, 0xf1, 0x76, 0x77, 0x22,
	0x6f, 0xfa, 0x23, 0xb7, 0xe3, 0x3e, 0x79, 0x6f, 0xbf, 0xb3, 0x86, 0x84, 0xfd, 0x8c, 0xff, 0x22,
	0x7c, 0x80, 0xfb, 0xbf, 0x5e, 0xf5, 0xc2, 0xf6, 0x4b, 0xa6, 0xaf, 0x6f, 0xe8, 0xa3, 0xbd, 0xfd,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x16, 0xe1, 0x30, 0x85, 0xfc, 0x03, 0x00, 0x00,
}
