// Code generated by protoc-gen-go. DO NOT EDIT.
// source: yr_totals.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type YearlyTotal struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Year                 string   `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Party                string   `protobuf:"bytes,4,opt,name=Party,proto3" json:"Party,omitempty"`
	Total                float32  `protobuf:"fixed32,5,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YearlyTotal) Reset()         { *m = YearlyTotal{} }
func (m *YearlyTotal) String() string { return proto.CompactTextString(m) }
func (*YearlyTotal) ProtoMessage()    {}
func (*YearlyTotal) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d5873f8130fc8d6, []int{0}
}

func (m *YearlyTotal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YearlyTotal.Unmarshal(m, b)
}
func (m *YearlyTotal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YearlyTotal.Marshal(b, m, deterministic)
}
func (m *YearlyTotal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YearlyTotal.Merge(m, src)
}
func (m *YearlyTotal) XXX_Size() int {
	return xxx_messageInfo_YearlyTotal.Size(m)
}
func (m *YearlyTotal) XXX_DiscardUnknown() {
	xxx_messageInfo_YearlyTotal.DiscardUnknown(m)
}

var xxx_messageInfo_YearlyTotal proto.InternalMessageInfo

func (m *YearlyTotal) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *YearlyTotal) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *YearlyTotal) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *YearlyTotal) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *YearlyTotal) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*YearlyTotal)(nil), "protobuf.YearlyTotal")
}

func init() { proto.RegisterFile("yr_totals.proto", fileDescriptor_1d5873f8130fc8d6) }

var fileDescriptor_1d5873f8130fc8d6 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xaf, 0x2c, 0x8a, 0x2f,
	0xc9, 0x2f, 0x49, 0xcc, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49,
	0xa5, 0x69, 0x4a, 0x95, 0x5c, 0xdc, 0x91, 0xa9, 0x89, 0x45, 0x39, 0x95, 0x21, 0x20, 0x79, 0x21,
	0x3e, 0x2e, 0x26, 0x4f, 0x17, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x26, 0x4f, 0x17, 0x21,
	0x21, 0x2e, 0x16, 0x90, 0xb4, 0x04, 0x13, 0x58, 0x04, 0xcc, 0x16, 0x92, 0xe2, 0xe2, 0x70, 0x4e,
	0x2c, 0x49, 0x4d, 0xcf, 0x2f, 0xaa, 0x94, 0x60, 0x06, 0x8b, 0xc3, 0xf9, 0x42, 0x22, 0x5c, 0xac,
	0x01, 0x89, 0x45, 0x25, 0x95, 0x12, 0x2c, 0x60, 0x09, 0x08, 0x07, 0x24, 0x0a, 0x36, 0x5e, 0x82,
	0x55, 0x81, 0x51, 0x83, 0x29, 0x08, 0xc2, 0x49, 0x62, 0x03, 0x3b, 0xc2, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x48, 0x28, 0xbd, 0x51, 0x9e, 0x00, 0x00, 0x00,
}
