// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cand.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CandEntry struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Total                float32  `protobuf:"fixed32,2,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandEntry) Reset()         { *m = CandEntry{} }
func (m *CandEntry) String() string { return proto.CompactTextString(m) }
func (*CandEntry) ProtoMessage()    {}
func (*CandEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_53ffa1b34967639c, []int{0}
}

func (m *CandEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandEntry.Unmarshal(m, b)
}
func (m *CandEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandEntry.Marshal(b, m, deterministic)
}
func (m *CandEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandEntry.Merge(m, src)
}
func (m *CandEntry) XXX_Size() int {
	return xxx_messageInfo_CandEntry.Size(m)
}
func (m *CandEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CandEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CandEntry proto.InternalMessageInfo

func (m *CandEntry) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CandEntry) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Candidate struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Party                string   `protobuf:"bytes,3,opt,name=Party,proto3" json:"Party,omitempty"`
	ElectnYr             int32    `protobuf:"varint,4,opt,name=ElectnYr,proto3" json:"ElectnYr,omitempty"`
	OfficeState          string   `protobuf:"bytes,5,opt,name=OfficeState,proto3" json:"OfficeState,omitempty"`
	Office               string   `protobuf:"bytes,6,opt,name=Office,proto3" json:"Office,omitempty"`
	PCC                  string   `protobuf:"bytes,7,opt,name=PCC,proto3" json:"PCC,omitempty"`
	City                 string   `protobuf:"bytes,8,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,9,opt,name=State,proto3" json:"State,omitempty"`
	Zip                  string   `protobuf:"bytes,10,opt,name=Zip,proto3" json:"Zip,omitempty"`
	OtherAffiliates      []string `protobuf:"bytes,11,rep,name=OtherAffiliates,proto3" json:"OtherAffiliates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_53ffa1b34967639c, []int{1}
}

func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (m *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(m, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Candidate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Candidate) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *Candidate) GetElectnYr() int32 {
	if m != nil {
		return m.ElectnYr
	}
	return 0
}

func (m *Candidate) GetOfficeState() string {
	if m != nil {
		return m.OfficeState
	}
	return ""
}

func (m *Candidate) GetOffice() string {
	if m != nil {
		return m.Office
	}
	return ""
}

func (m *Candidate) GetPCC() string {
	if m != nil {
		return m.PCC
	}
	return ""
}

func (m *Candidate) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Candidate) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Candidate) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Candidate) GetOtherAffiliates() []string {
	if m != nil {
		return m.OtherAffiliates
	}
	return nil
}

func init() {
	proto.RegisterType((*CandEntry)(nil), "protobuf.CandEntry")
	proto.RegisterType((*Candidate)(nil), "protobuf.Candidate")
}

func init() { proto.RegisterFile("cand.proto", fileDescriptor_53ffa1b34967639c) }

var fileDescriptor_53ffa1b34967639c = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x14, 0x84, 0x69, 0xbb, 0xad, 0xcd, 0x5b, 0xd0, 0x25, 0x88, 0x3c, 0x3c, 0x85, 0x3d, 0xe5, 0x24,
	0x88, 0xbf, 0x40, 0xba, 0x7b, 0xd8, 0x8b, 0xbb, 0x44, 0x2f, 0xee, 0x2d, 0xdb, 0x26, 0x18, 0xa8,
	0x6d, 0x89, 0xcf, 0x43, 0x7f, 0x87, 0x7f, 0x58, 0x92, 0x88, 0x88, 0x7b, 0xca, 0xcc, 0x84, 0x6f,
	0x18, 0x1e, 0x40, 0xab, 0x87, 0xee, 0x6e, 0xf2, 0x23, 0x8d, 0xbc, 0x8e, 0xcf, 0xe9, 0xd3, 0xae,
	0xef, 0x81, 0x35, 0x7a, 0xe8, 0xb6, 0x03, 0xf9, 0x99, 0x5f, 0x42, 0xbe, 0xdb, 0x60, 0x26, 0x32,
	0xc9, 0x54, 0xbe, 0xdb, 0xf0, 0x6b, 0x28, 0x5f, 0x46, 0xd2, 0x3d, 0xe6, 0x22, 0x93, 0xb9, 0x4a,
	0x66, 0xfd, 0x95, 0x27, 0xc6, 0x75, 0x9a, 0xcc, 0x19, 0xc3, 0x61, 0xf1, 0xa4, 0xdf, 0x4d, 0x44,
	0x98, 0x8a, 0x3a, 0xf4, 0x1c, 0xb4, 0xa7, 0x19, 0x8b, 0x18, 0x26, 0xc3, 0x6f, 0xa1, 0xde, 0xf6,
	0xa6, 0xa5, 0xe1, 0xd5, 0xe3, 0x42, 0x64, 0xb2, 0x54, 0xbf, 0x9e, 0x0b, 0x58, 0xee, 0xad, 0x75,
	0xad, 0x79, 0x26, 0x4d, 0x06, 0xcb, 0xc8, 0xfd, 0x8d, 0xf8, 0x0d, 0x54, 0xc9, 0x62, 0x15, 0x3f,
	0x7f, 0x1c, 0x5f, 0x41, 0x71, 0x68, 0x1a, 0xbc, 0x88, 0x61, 0x90, 0x61, 0x51, 0xe3, 0x68, 0xc6,
	0x3a, 0x2d, 0x0a, 0x3a, 0x2c, 0x4a, 0xcd, 0x2c, 0x2d, 0x4a, 0x9d, 0x2b, 0x28, 0x8e, 0x6e, 0x42,
	0x48, 0xec, 0xd1, 0x4d, 0x5c, 0xc2, 0xd5, 0x9e, 0xde, 0x8c, 0x7f, 0xb4, 0xd6, 0xf5, 0x4e, 0x93,
	0xf9, 0xc0, 0xa5, 0x28, 0x24, 0x53, 0xff, 0xe3, 0x53, 0x15, 0x4f, 0xfa, 0xf0, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0xbf, 0xf8, 0x47, 0x0e, 0x67, 0x01, 0x00, 0x00,
}
