// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmte.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Committee struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	TresName             string   `protobuf:"bytes,3,opt,name=TresName,proto3" json:"TresName,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,5,opt,name=State,proto3" json:"State,omitempty"`
	Zip                  string   `protobuf:"bytes,6,opt,name=Zip,proto3" json:"Zip,omitempty"`
	Designation          string   `protobuf:"bytes,7,opt,name=Designation,proto3" json:"Designation,omitempty"`
	Type                 string   `protobuf:"bytes,8,opt,name=Type,proto3" json:"Type,omitempty"`
	Party                string   `protobuf:"bytes,9,opt,name=Party,proto3" json:"Party,omitempty"`
	FilingFreq           string   `protobuf:"bytes,10,opt,name=FilingFreq,proto3" json:"FilingFreq,omitempty"`
	OrgType              string   `protobuf:"bytes,11,opt,name=OrgType,proto3" json:"OrgType,omitempty"`
	ConnectedOrg         string   `protobuf:"bytes,12,opt,name=ConnectedOrg,proto3" json:"ConnectedOrg,omitempty"`
	CandID               string   `protobuf:"bytes,13,opt,name=CandID,proto3" json:"CandID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Committee) Reset()         { *m = Committee{} }
func (m *Committee) String() string { return proto.CompactTextString(m) }
func (*Committee) ProtoMessage()    {}
func (*Committee) Descriptor() ([]byte, []int) {
	return fileDescriptor_007568e14edd570b, []int{0}
}

func (m *Committee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Committee.Unmarshal(m, b)
}
func (m *Committee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Committee.Marshal(b, m, deterministic)
}
func (m *Committee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Committee.Merge(m, src)
}
func (m *Committee) XXX_Size() int {
	return xxx_messageInfo_Committee.Size(m)
}
func (m *Committee) XXX_DiscardUnknown() {
	xxx_messageInfo_Committee.DiscardUnknown(m)
}

var xxx_messageInfo_Committee proto.InternalMessageInfo

func (m *Committee) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Committee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Committee) GetTresName() string {
	if m != nil {
		return m.TresName
	}
	return ""
}

func (m *Committee) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Committee) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Committee) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Committee) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *Committee) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Committee) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *Committee) GetFilingFreq() string {
	if m != nil {
		return m.FilingFreq
	}
	return ""
}

func (m *Committee) GetOrgType() string {
	if m != nil {
		return m.OrgType
	}
	return ""
}

func (m *Committee) GetConnectedOrg() string {
	if m != nil {
		return m.ConnectedOrg
	}
	return ""
}

func (m *Committee) GetCandID() string {
	if m != nil {
		return m.CandID
	}
	return ""
}

func init() {
	proto.RegisterType((*Committee)(nil), "protobuf.Committee")
}

func init() { proto.RegisterFile("cmte.proto", fileDescriptor_007568e14edd570b) }

var fileDescriptor_007568e14edd570b = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x69, 0xda, 0xa6, 0xc9, 0xb4, 0x8a, 0x0c, 0x22, 0x83, 0x07, 0x29, 0x3d, 0x79, 0xf2,
	0xe2, 0x23, 0x24, 0x14, 0x72, 0xb1, 0xa2, 0x3d, 0x79, 0xdb, 0xb6, 0x63, 0x58, 0x30, 0xbb, 0x71,
	0x3b, 0x1e, 0xf2, 0x88, 0xbe, 0x95, 0xec, 0xac, 0x4a, 0x7b, 0xda, 0xff, 0xff, 0xfe, 0xe1, 0x3b,
	0x2c, 0xc0, 0xbe, 0x13, 0x7e, 0xe8, 0x83, 0x17, 0x8f, 0x85, 0x3e, 0xbb, 0xaf, 0xf7, 0xd5, 0x77,
	0x06, 0x65, 0xe5, 0xbb, 0xce, 0x8a, 0x30, 0xe3, 0x25, 0x64, 0x4d, 0x4d, 0xa3, 0xe5, 0xe8, 0xbe,
	0x7c, 0xc9, 0x9a, 0x1a, 0x11, 0x26, 0x4f, 0xa6, 0x63, 0xca, 0x94, 0x68, 0xc6, 0x5b, 0x28, 0xb6,
	0x81, 0x8f, 0xca, 0xc7, 0xca, 0xff, 0x7b, 0xbc, 0xaf, 0xac, 0x0c, 0x34, 0x49, 0xf7, 0x31, 0xe3,
	0x35, 0x4c, 0x5f, 0xc5, 0x08, 0xd3, 0x54, 0x61, 0x2a, 0x78, 0x05, 0xe3, 0x37, 0xdb, 0x53, 0xae,
	0x2c, 0x46, 0x5c, 0xc2, 0xbc, 0xe6, 0xa3, 0x6d, 0x9d, 0x11, 0xeb, 0x1d, 0xcd, 0x74, 0x39, 0x45,
	0xd1, 0xbe, 0x1d, 0x7a, 0xa6, 0x22, 0xd9, 0x63, 0x8e, 0xf6, 0x67, 0x13, 0x64, 0xa0, 0x32, 0xd9,
	0xb5, 0xe0, 0x1d, 0xc0, 0xda, 0x7e, 0x58, 0xd7, 0xae, 0x03, 0x7f, 0x12, 0xe8, 0x74, 0x42, 0x90,
	0x60, 0xb6, 0x09, 0xad, 0xca, 0xe6, 0x3a, 0xfe, 0x55, 0x5c, 0xc1, 0xa2, 0xf2, 0xce, 0xf1, 0x5e,
	0xf8, 0xb0, 0x09, 0x2d, 0x2d, 0x74, 0x3e, 0x63, 0x78, 0x03, 0x79, 0x65, 0xdc, 0xa1, 0xa9, 0xe9,
	0x42, 0xd7, 0xdf, 0xb6, 0xcb, 0xf5, 0x57, 0x1f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x4e,
	0x5d, 0xc1, 0x6a, 0x01, 0x00, 0x00,
}
