// Code generated by protoc-gen-go. DO NOT EDIT.
// source: disb.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Disbursement struct {
	CmteID               string               `protobuf:"bytes,1,opt,name=CmteID,proto3" json:"CmteID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	City                 string               `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	State                string               `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`
	Zip                  string               `protobuf:"bytes,5,opt,name=Zip,proto3" json:"Zip,omitempty"`
	TxDate               *timestamp.Timestamp `protobuf:"bytes,6,opt,name=TxDate,proto3" json:"TxDate,omitempty"`
	TxAmt                float32              `protobuf:"fixed32,7,opt,name=TxAmt,proto3" json:"TxAmt,omitempty"`
	TxPGI                string               `protobuf:"bytes,8,opt,name=TxPGI,proto3" json:"TxPGI,omitempty"`
	Purpose              string               `protobuf:"bytes,9,opt,name=Purpose,proto3" json:"Purpose,omitempty"`
	Category             string               `protobuf:"bytes,10,opt,name=Category,proto3" json:"Category,omitempty"`
	CategoryDesc         string               `protobuf:"bytes,15,opt,name=CategoryDesc,proto3" json:"CategoryDesc,omitempty"`
	MemoTxt              string               `protobuf:"bytes,16,opt,name=MemoTxt,proto3" json:"MemoTxt,omitempty"`
	EntityType           string               `protobuf:"bytes,17,opt,name=EntityType,proto3" json:"EntityType,omitempty"`
	SubID                int32                `protobuf:"varint,18,opt,name=SubID,proto3" json:"SubID,omitempty"`
	FileNum              int32                `protobuf:"varint,19,opt,name=FileNum,proto3" json:"FileNum,omitempty"`
	TxID                 string               `protobuf:"bytes,20,opt,name=TxID,proto3" json:"TxID,omitempty"`
	BackRefTxID          string               `protobuf:"bytes,21,opt,name=BackRefTxID,proto3" json:"BackRefTxID,omitempty"`
	RecID                string               `protobuf:"bytes,22,opt,name=RecID,proto3" json:"RecID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Disbursement) Reset()         { *m = Disbursement{} }
func (m *Disbursement) String() string { return proto.CompactTextString(m) }
func (*Disbursement) ProtoMessage()    {}
func (*Disbursement) Descriptor() ([]byte, []int) {
	return fileDescriptor_3046b3b9aab302e4, []int{0}
}

func (m *Disbursement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disbursement.Unmarshal(m, b)
}
func (m *Disbursement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disbursement.Marshal(b, m, deterministic)
}
func (m *Disbursement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disbursement.Merge(m, src)
}
func (m *Disbursement) XXX_Size() int {
	return xxx_messageInfo_Disbursement.Size(m)
}
func (m *Disbursement) XXX_DiscardUnknown() {
	xxx_messageInfo_Disbursement.DiscardUnknown(m)
}

var xxx_messageInfo_Disbursement proto.InternalMessageInfo

func (m *Disbursement) GetCmteID() string {
	if m != nil {
		return m.CmteID
	}
	return ""
}

func (m *Disbursement) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Disbursement) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Disbursement) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Disbursement) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Disbursement) GetTxDate() *timestamp.Timestamp {
	if m != nil {
		return m.TxDate
	}
	return nil
}

func (m *Disbursement) GetTxAmt() float32 {
	if m != nil {
		return m.TxAmt
	}
	return 0
}

func (m *Disbursement) GetTxPGI() string {
	if m != nil {
		return m.TxPGI
	}
	return ""
}

func (m *Disbursement) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *Disbursement) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Disbursement) GetCategoryDesc() string {
	if m != nil {
		return m.CategoryDesc
	}
	return ""
}

func (m *Disbursement) GetMemoTxt() string {
	if m != nil {
		return m.MemoTxt
	}
	return ""
}

func (m *Disbursement) GetEntityType() string {
	if m != nil {
		return m.EntityType
	}
	return ""
}

func (m *Disbursement) GetSubID() int32 {
	if m != nil {
		return m.SubID
	}
	return 0
}

func (m *Disbursement) GetFileNum() int32 {
	if m != nil {
		return m.FileNum
	}
	return 0
}

func (m *Disbursement) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *Disbursement) GetBackRefTxID() string {
	if m != nil {
		return m.BackRefTxID
	}
	return ""
}

func (m *Disbursement) GetRecID() string {
	if m != nil {
		return m.RecID
	}
	return ""
}

func init() {
	proto.RegisterType((*Disbursement)(nil), "protobuf.Disbursement")
}

func init() { proto.RegisterFile("disb.proto", fileDescriptor_3046b3b9aab302e4) }

var fileDescriptor_3046b3b9aab302e4 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x6f, 0xb2, 0x40,
	0x10, 0x87, 0x83, 0x7f, 0x50, 0x47, 0x93, 0xd7, 0x77, 0x6b, 0xcd, 0xc4, 0x43, 0x4b, 0x3c, 0x71,
	0xc2, 0xc4, 0x7e, 0x82, 0x56, 0xda, 0x86, 0x43, 0x8d, 0xa1, 0x9c, 0x7a, 0x03, 0x3b, 0x1a, 0x52,
	0x57, 0x08, 0x2c, 0x09, 0x7c, 0xe1, 0x7e, 0x8e, 0x66, 0x67, 0xa5, 0xb1, 0xa7, 0x9d, 0xe7, 0x99,
	0xc9, 0xec, 0xe4, 0x07, 0xf0, 0x99, 0x96, 0x89, 0x97, 0x17, 0x99, 0xca, 0xc4, 0x90, 0x9f, 0xa4,
	0x3a, 0x2c, 0xee, 0x8f, 0x59, 0x76, 0x3c, 0xd1, 0xaa, 0x15, 0x2b, 0x95, 0x4a, 0x2a, 0x55, 0x2c,
	0x73, 0x33, 0xba, 0xfc, 0xee, 0xc2, 0xc4, 0x4f, 0xcb, 0xa4, 0x2a, 0x4a, 0x92, 0x74, 0x56, 0x62,
	0x0e, 0xf6, 0x46, 0x2a, 0x0a, 0x7c, 0xb4, 0x1c, 0xcb, 0x1d, 0x85, 0x17, 0x12, 0x02, 0x7a, 0xdb,
	0x58, 0x12, 0x76, 0xd8, 0x72, 0xad, 0xdd, 0x26, 0x55, 0x0d, 0x76, 0x8d, 0xd3, 0xb5, 0x98, 0x41,
	0xff, 0x5d, 0xc5, 0x8a, 0xb0, 0xc7, 0xd2, 0x80, 0x98, 0x42, 0xf7, 0x23, 0xcd, 0xb1, 0xcf, 0x4e,
	0x97, 0x62, 0x0d, 0x76, 0x54, 0xfb, 0x7a, 0xd0, 0x76, 0x2c, 0x77, 0xbc, 0x5e, 0x78, 0xe6, 0x54,
	0xaf, 0x3d, 0xd5, 0x8b, 0xda, 0x53, 0xc3, 0xcb, 0xa4, 0xde, 0x1d, 0xd5, 0x8f, 0x52, 0xe1, 0xc0,
	0xb1, 0xdc, 0x4e, 0x68, 0xc0, 0xd8, 0xdd, 0x6b, 0x80, 0x43, 0xf3, 0x23, 0x83, 0x40, 0x18, 0xec,
	0xaa, 0x22, 0xcf, 0x4a, 0xc2, 0x11, 0xfb, 0x16, 0xc5, 0x02, 0x86, 0x9b, 0x58, 0xd1, 0x31, 0x2b,
	0x1a, 0x04, 0x6e, 0xfd, 0xb2, 0x58, 0xc2, 0xa4, 0xad, 0x7d, 0x2a, 0xf7, 0xf8, 0x8f, 0xfb, 0x7f,
	0x9c, 0xde, 0xfc, 0x46, 0x32, 0x8b, 0x6a, 0x85, 0x53, 0xb3, 0xf9, 0x82, 0xe2, 0x0e, 0xe0, 0xf9,
	0xac, 0x52, 0xd5, 0x44, 0x4d, 0x4e, 0xf8, 0x9f, 0x9b, 0x57, 0x86, 0xb3, 0xa9, 0x92, 0xc0, 0x47,
	0xe1, 0x58, 0x6e, 0x3f, 0x34, 0xa0, 0xf7, 0xbd, 0xa4, 0x27, 0xda, 0x56, 0x12, 0x6f, 0xd8, 0xb7,
	0xa8, 0xf3, 0x8d, 0xea, 0xc0, 0xc7, 0x99, 0xc9, 0x57, 0xd7, 0xc2, 0x81, 0xf1, 0x53, 0xbc, 0xff,
	0x0a, 0xe9, 0xc0, 0xad, 0x5b, 0x6e, 0x5d, 0x2b, 0xfd, 0x4b, 0x48, 0xfb, 0xc0, 0xc7, 0xb9, 0xc9,
	0x83, 0x21, 0xb1, 0x39, 0xd7, 0x87, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x34, 0xe4, 0x76,
	0x28, 0x02, 0x00, 0x00,
}
