// Code generated by protoc-gen-go. DO NOT EDIT.
// source: id_lookup.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Lookup struct {
	DonorID              map[string]string `protobuf:"bytes,1,rep,name=donorID,proto3" json:"donorID,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Lookup) Reset()         { *m = Lookup{} }
func (m *Lookup) String() string { return proto.CompactTextString(m) }
func (*Lookup) ProtoMessage()    {}
func (*Lookup) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed13c4573720b112, []int{0}
}

func (m *Lookup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lookup.Unmarshal(m, b)
}
func (m *Lookup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lookup.Marshal(b, m, deterministic)
}
func (m *Lookup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lookup.Merge(m, src)
}
func (m *Lookup) XXX_Size() int {
	return xxx_messageInfo_Lookup.Size(m)
}
func (m *Lookup) XXX_DiscardUnknown() {
	xxx_messageInfo_Lookup.DiscardUnknown(m)
}

var xxx_messageInfo_Lookup proto.InternalMessageInfo

func (m *Lookup) GetDonorID() map[string]string {
	if m != nil {
		return m.DonorID
	}
	return nil
}

func init() {
	proto.RegisterType((*Lookup)(nil), "protobuf.Lookup")
	proto.RegisterMapType((map[string]string)(nil), "protobuf.Lookup.DonorIDEntry")
}

func init() { proto.RegisterFile("id_lookup.proto", fileDescriptor_ed13c4573720b112) }

var fileDescriptor_ed13c4573720b112 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x4c, 0x89, 0xcf,
	0xc9, 0xcf, 0xcf, 0x2e, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49,
	0xa5, 0x69, 0x4a, 0xb5, 0x5c, 0x6c, 0x3e, 0x60, 0x19, 0x21, 0x73, 0x2e, 0xf6, 0x94, 0xfc, 0xbc,
	0xfc, 0x22, 0x4f, 0x17, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x59, 0x3d, 0x98, 0x2a, 0x3d,
	0x88, 0x12, 0x3d, 0x17, 0x88, 0xbc, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0x4c, 0xb5, 0x94, 0x15,
	0x17, 0x0f, 0xb2, 0x84, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x88, 0x29, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x2a, 0xc1, 0x04, 0x16,
	0x83, 0x70, 0xac, 0x98, 0x2c, 0x18, 0x93, 0xd8, 0xc0, 0x56, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x49, 0x2f, 0xf8, 0x38, 0xa2, 0x00, 0x00, 0x00,
}
