// Code generated by protoc-gen-go. DO NOT EDIT.
// source: indv_cont.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IndvContribution struct {
	CmteID               string               `protobuf:"bytes,1,opt,name=CmteID,proto3" json:"CmteID,omitempty"`
	AmndtInd             string               `protobuf:"bytes,2,opt,name=AmndtInd,proto3" json:"AmndtInd,omitempty"`
	ReportType           string               `protobuf:"bytes,3,opt,name=ReportType,proto3" json:"ReportType,omitempty"`
	TxPGI                string               `protobuf:"bytes,4,opt,name=TxPGI,proto3" json:"TxPGI,omitempty"`
	ImgNum               string               `protobuf:"bytes,5,opt,name=imgNum,proto3" json:"imgNum,omitempty"`
	TxType               string               `protobuf:"bytes,6,opt,name=TxType,proto3" json:"TxType,omitempty"`
	EntityType           string               `protobuf:"bytes,7,opt,name=EntityType,proto3" json:"EntityType,omitempty"`
	Name                 string               `protobuf:"bytes,8,opt,name=Name,proto3" json:"Name,omitempty"`
	City                 string               `protobuf:"bytes,9,opt,name=City,proto3" json:"City,omitempty"`
	State                string               `protobuf:"bytes,10,opt,name=State,proto3" json:"State,omitempty"`
	Zip                  string               `protobuf:"bytes,11,opt,name=Zip,proto3" json:"Zip,omitempty"`
	Employer             string               `protobuf:"bytes,12,opt,name=Employer,proto3" json:"Employer,omitempty"`
	Occupation           string               `protobuf:"bytes,13,opt,name=Occupation,proto3" json:"Occupation,omitempty"`
	DonorID              string               `protobuf:"bytes,14,opt,name=DonorID,proto3" json:"DonorID,omitempty"`
	TxDate               *timestamp.Timestamp `protobuf:"bytes,15,opt,name=TxDate,proto3" json:"TxDate,omitempty"`
	TxAmt                float32              `protobuf:"fixed32,16,opt,name=TxAmt,proto3" json:"TxAmt,omitempty"`
	OtherID              string               `protobuf:"bytes,17,opt,name=OtherID,proto3" json:"OtherID,omitempty"`
	TxID                 string               `protobuf:"bytes,18,opt,name=TxID,proto3" json:"TxID,omitempty"`
	FileNum              int32                `protobuf:"varint,19,opt,name=FileNum,proto3" json:"FileNum,omitempty"`
	MemoCode             string               `protobuf:"bytes,20,opt,name=MemoCode,proto3" json:"MemoCode,omitempty"`
	MemoText             string               `protobuf:"bytes,21,opt,name=MemoText,proto3" json:"MemoText,omitempty"`
	SubID                int32                `protobuf:"varint,22,opt,name=SubID,proto3" json:"SubID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *IndvContribution) Reset()         { *m = IndvContribution{} }
func (m *IndvContribution) String() string { return proto.CompactTextString(m) }
func (*IndvContribution) ProtoMessage()    {}
func (*IndvContribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_df2bc02425e1321a, []int{0}
}

func (m *IndvContribution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndvContribution.Unmarshal(m, b)
}
func (m *IndvContribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndvContribution.Marshal(b, m, deterministic)
}
func (m *IndvContribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndvContribution.Merge(m, src)
}
func (m *IndvContribution) XXX_Size() int {
	return xxx_messageInfo_IndvContribution.Size(m)
}
func (m *IndvContribution) XXX_DiscardUnknown() {
	xxx_messageInfo_IndvContribution.DiscardUnknown(m)
}

var xxx_messageInfo_IndvContribution proto.InternalMessageInfo

func (m *IndvContribution) GetCmteID() string {
	if m != nil {
		return m.CmteID
	}
	return ""
}

func (m *IndvContribution) GetAmndtInd() string {
	if m != nil {
		return m.AmndtInd
	}
	return ""
}

func (m *IndvContribution) GetReportType() string {
	if m != nil {
		return m.ReportType
	}
	return ""
}

func (m *IndvContribution) GetTxPGI() string {
	if m != nil {
		return m.TxPGI
	}
	return ""
}

func (m *IndvContribution) GetImgNum() string {
	if m != nil {
		return m.ImgNum
	}
	return ""
}

func (m *IndvContribution) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

func (m *IndvContribution) GetEntityType() string {
	if m != nil {
		return m.EntityType
	}
	return ""
}

func (m *IndvContribution) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IndvContribution) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *IndvContribution) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *IndvContribution) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *IndvContribution) GetEmployer() string {
	if m != nil {
		return m.Employer
	}
	return ""
}

func (m *IndvContribution) GetOccupation() string {
	if m != nil {
		return m.Occupation
	}
	return ""
}

func (m *IndvContribution) GetDonorID() string {
	if m != nil {
		return m.DonorID
	}
	return ""
}

func (m *IndvContribution) GetTxDate() *timestamp.Timestamp {
	if m != nil {
		return m.TxDate
	}
	return nil
}

func (m *IndvContribution) GetTxAmt() float32 {
	if m != nil {
		return m.TxAmt
	}
	return 0
}

func (m *IndvContribution) GetOtherID() string {
	if m != nil {
		return m.OtherID
	}
	return ""
}

func (m *IndvContribution) GetTxID() string {
	if m != nil {
		return m.TxID
	}
	return ""
}

func (m *IndvContribution) GetFileNum() int32 {
	if m != nil {
		return m.FileNum
	}
	return 0
}

func (m *IndvContribution) GetMemoCode() string {
	if m != nil {
		return m.MemoCode
	}
	return ""
}

func (m *IndvContribution) GetMemoText() string {
	if m != nil {
		return m.MemoText
	}
	return ""
}

func (m *IndvContribution) GetSubID() int32 {
	if m != nil {
		return m.SubID
	}
	return 0
}

func init() {
	proto.RegisterType((*IndvContribution)(nil), "protobuf.IndvContribution")
}

func init() { proto.RegisterFile("indv_cont.proto", fileDescriptor_df2bc02425e1321a) }

var fileDescriptor_df2bc02425e1321a = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0xe5, 0x36, 0x49, 0xd3, 0x2d, 0xd0, 0xb0, 0x94, 0x6a, 0x94, 0x03, 0x58, 0x9c, 0x7c,
	0x72, 0xa5, 0xf2, 0x0b, 0x2a, 0xbb, 0x20, 0x1f, 0x48, 0x90, 0xf1, 0x89, 0x0b, 0xb2, 0xe3, 0x25,
	0xac, 0x94, 0xdd, 0xb5, 0xcc, 0x38, 0xb2, 0xff, 0x26, 0xbf, 0x08, 0xcd, 0x4e, 0x96, 0x70, 0xf2,
	0x7e, 0xef, 0xad, 0xfc, 0xe6, 0xcd, 0x8a, 0x5b, 0x6d, 0xdb, 0xe3, 0x8f, 0x9d, 0xb3, 0x98, 0x76,
	0xbd, 0x43, 0x27, 0x97, 0xfe, 0xd3, 0x0c, 0x3f, 0xd7, 0xef, 0xf7, 0xce, 0xed, 0x0f, 0xea, 0x21,
	0x08, 0x0f, 0xa8, 0x8d, 0xfa, 0x8d, 0xb5, 0xe9, 0xf8, 0xea, 0x87, 0x3f, 0x33, 0xb1, 0x2a, 0x6c,
	0x7b, 0xcc, 0x9c, 0xc5, 0x5e, 0x37, 0x03, 0x6a, 0x67, 0xe5, 0xbd, 0x58, 0x64, 0x06, 0x55, 0x91,
	0x43, 0x14, 0x47, 0xc9, 0x75, 0x79, 0x22, 0xb9, 0x16, 0xcb, 0x27, 0x63, 0x5b, 0x2c, 0x6c, 0x0b,
	0x17, 0xde, 0xf9, 0xc7, 0xf2, 0x9d, 0x10, 0xa5, 0xea, 0x5c, 0x8f, 0xd5, 0xd4, 0x29, 0xb8, 0xf4,
	0xee, 0x7f, 0x8a, 0xbc, 0x13, 0xf3, 0x6a, 0xfc, 0xfa, 0xb9, 0x80, 0x99, 0xb7, 0x18, 0x28, 0x49,
	0x9b, 0xfd, 0x66, 0x30, 0x30, 0xe7, 0x24, 0x26, 0xd2, 0xab, 0xd1, 0xff, 0x69, 0xc1, 0x3a, 0x13,
	0xa5, 0x3c, 0x5b, 0xd4, 0x38, 0x79, 0xef, 0x8a, 0x53, 0xce, 0x8a, 0x94, 0x62, 0xb6, 0xa9, 0x8d,
	0x82, 0xa5, 0x77, 0xfc, 0x99, 0xb4, 0x4c, 0xe3, 0x04, 0xd7, 0xac, 0xd1, 0x99, 0xa6, 0xf9, 0x86,
	0x35, 0x2a, 0x10, 0x3c, 0x8d, 0x07, 0xb9, 0x12, 0x97, 0xdf, 0x75, 0x07, 0x37, 0x5e, 0xa3, 0x23,
	0x35, 0x7e, 0x36, 0xdd, 0xc1, 0x4d, 0xaa, 0x87, 0x17, 0xdc, 0x38, 0x30, 0xcd, 0xb2, 0xdd, 0xed,
	0x86, 0xae, 0xa6, 0x9d, 0xc1, 0x4b, 0x9e, 0xe5, 0xac, 0x48, 0x10, 0x57, 0xb9, 0xb3, 0xae, 0x2f,
	0x72, 0x78, 0xe5, 0xcd, 0x80, 0xf2, 0x91, 0xda, 0xe5, 0x14, 0x7f, 0x1b, 0x47, 0xc9, 0xcd, 0xe3,
	0x3a, 0xe5, 0x67, 0x4a, 0xc3, 0x33, 0xa5, 0x55, 0x78, 0xa6, 0xf2, 0x74, 0x93, 0xf7, 0xf7, 0x64,
	0x10, 0x56, 0x71, 0x94, 0x5c, 0x94, 0x0c, 0x94, 0xb1, 0xc5, 0x5f, 0x8a, 0x32, 0x5e, 0x73, 0xc6,
	0x09, 0xa9, 0x75, 0x35, 0x16, 0x39, 0x48, 0x6e, 0x4d, 0x67, 0xba, 0xfd, 0x49, 0x1f, 0x14, 0xad,
	0xfb, 0x4d, 0x1c, 0x25, 0xf3, 0x32, 0x20, 0xf5, 0xfc, 0xa2, 0x8c, 0xcb, 0x5c, 0xab, 0xe0, 0x8e,
	0x7b, 0x06, 0x0e, 0x5e, 0xa5, 0x46, 0x84, 0xb7, 0x67, 0x8f, 0xd8, 0xef, 0x71, 0x68, 0x8a, 0x1c,
	0xee, 0xfd, 0xff, 0x18, 0x9a, 0x85, 0xef, 0xf1, 0xf1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa,
	0x3a, 0x0f, 0xec, 0x99, 0x02, 0x00, 0x00,
}
