// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type SearchRequest struct {
	UID                  string               `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Text                 string               `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Msg                  string               `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *SearchRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SearchRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *SearchRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SearchResponse struct {
	UID                  string               `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Results              []*SearchResult      `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Msg                  string               `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *SearchResponse) GetResults() []*SearchResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *SearchResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *SearchResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SearchResult struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`
	Years                []string `protobuf:"bytes,5,rep,name=Years,proto3" json:"Years,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResult) Reset()         { *m = SearchResult{} }
func (m *SearchResult) String() string { return proto.CompactTextString(m) }
func (*SearchResult) ProtoMessage()    {}
func (*SearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *SearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResult.Unmarshal(m, b)
}
func (m *SearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResult.Marshal(b, m, deterministic)
}
func (m *SearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResult.Merge(m, src)
}
func (m *SearchResult) XXX_Size() int {
	return xxx_messageInfo_SearchResult.Size(m)
}
func (m *SearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResult proto.InternalMessageInfo

func (m *SearchResult) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SearchResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchResult) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SearchResult) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SearchResult) GetYears() []string {
	if m != nil {
		return m.Years
	}
	return nil
}

type RankingsRequest struct {
	UID                  string               `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Year                 string               `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	Bucket               string               `protobuf:"bytes,3,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Category             string               `protobuf:"bytes,4,opt,name=Category,proto3" json:"Category,omitempty"`
	Party                string               `protobuf:"bytes,5,opt,name=Party,proto3" json:"Party,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Msg                  string               `protobuf:"bytes,7,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RankingsRequest) Reset()         { *m = RankingsRequest{} }
func (m *RankingsRequest) String() string { return proto.CompactTextString(m) }
func (*RankingsRequest) ProtoMessage()    {}
func (*RankingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *RankingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankingsRequest.Unmarshal(m, b)
}
func (m *RankingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankingsRequest.Marshal(b, m, deterministic)
}
func (m *RankingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankingsRequest.Merge(m, src)
}
func (m *RankingsRequest) XXX_Size() int {
	return xxx_messageInfo_RankingsRequest.Size(m)
}
func (m *RankingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RankingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RankingsRequest proto.InternalMessageInfo

func (m *RankingsRequest) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *RankingsRequest) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *RankingsRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *RankingsRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *RankingsRequest) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *RankingsRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *RankingsRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RankingsResponse struct {
	UID                  string               `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Rankings             *RankingsResult      `protobuf:"bytes,2,opt,name=Rankings,proto3" json:"Rankings,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Msg                  string               `protobuf:"bytes,8,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RankingsResponse) Reset()         { *m = RankingsResponse{} }
func (m *RankingsResponse) String() string { return proto.CompactTextString(m) }
func (*RankingsResponse) ProtoMessage()    {}
func (*RankingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *RankingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankingsResponse.Unmarshal(m, b)
}
func (m *RankingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankingsResponse.Marshal(b, m, deterministic)
}
func (m *RankingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankingsResponse.Merge(m, src)
}
func (m *RankingsResponse) XXX_Size() int {
	return xxx_messageInfo_RankingsResponse.Size(m)
}
func (m *RankingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RankingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RankingsResponse proto.InternalMessageInfo

func (m *RankingsResponse) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *RankingsResponse) GetRankings() *RankingsResult {
	if m != nil {
		return m.Rankings
	}
	return nil
}

func (m *RankingsResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *RankingsResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RankingsResult struct {
	ID                   string             `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Year                 string             `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	Bucket               string             `protobuf:"bytes,3,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Category             string             `protobuf:"bytes,4,opt,name=Category,proto3" json:"Category,omitempty"`
	Party                string             `protobuf:"bytes,5,opt,name=Party,proto3" json:"Party,omitempty"`
	RankingsList         map[string]float32 `protobuf:"bytes,6,rep,name=RankingsList,proto3" json:"RankingsList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RankingsResult) Reset()         { *m = RankingsResult{} }
func (m *RankingsResult) String() string { return proto.CompactTextString(m) }
func (*RankingsResult) ProtoMessage()    {}
func (*RankingsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *RankingsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankingsResult.Unmarshal(m, b)
}
func (m *RankingsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankingsResult.Marshal(b, m, deterministic)
}
func (m *RankingsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankingsResult.Merge(m, src)
}
func (m *RankingsResult) XXX_Size() int {
	return xxx_messageInfo_RankingsResult.Size(m)
}
func (m *RankingsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RankingsResult.DiscardUnknown(m)
}

var xxx_messageInfo_RankingsResult proto.InternalMessageInfo

func (m *RankingsResult) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RankingsResult) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *RankingsResult) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *RankingsResult) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *RankingsResult) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *RankingsResult) GetRankingsList() map[string]float32 {
	if m != nil {
		return m.RankingsList
	}
	return nil
}

type YrTotalRequest struct {
	UID                  string               `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Year                 string               `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	Category             string               `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Party                string               `protobuf:"bytes,4,opt,name=Party,proto3" json:"Party,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Msg                  string               `protobuf:"bytes,6,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *YrTotalRequest) Reset()         { *m = YrTotalRequest{} }
func (m *YrTotalRequest) String() string { return proto.CompactTextString(m) }
func (*YrTotalRequest) ProtoMessage()    {}
func (*YrTotalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *YrTotalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YrTotalRequest.Unmarshal(m, b)
}
func (m *YrTotalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YrTotalRequest.Marshal(b, m, deterministic)
}
func (m *YrTotalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YrTotalRequest.Merge(m, src)
}
func (m *YrTotalRequest) XXX_Size() int {
	return xxx_messageInfo_YrTotalRequest.Size(m)
}
func (m *YrTotalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_YrTotalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_YrTotalRequest proto.InternalMessageInfo

func (m *YrTotalRequest) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *YrTotalRequest) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *YrTotalRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *YrTotalRequest) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *YrTotalRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *YrTotalRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type YrTotalResponse struct {
	UID                  string               `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	YearlyTotal          *YrTotalResult       `protobuf:"bytes,2,opt,name=YearlyTotal,proto3" json:"YearlyTotal,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Msg                  string               `protobuf:"bytes,7,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *YrTotalResponse) Reset()         { *m = YrTotalResponse{} }
func (m *YrTotalResponse) String() string { return proto.CompactTextString(m) }
func (*YrTotalResponse) ProtoMessage()    {}
func (*YrTotalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{8}
}

func (m *YrTotalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YrTotalResponse.Unmarshal(m, b)
}
func (m *YrTotalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YrTotalResponse.Marshal(b, m, deterministic)
}
func (m *YrTotalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YrTotalResponse.Merge(m, src)
}
func (m *YrTotalResponse) XXX_Size() int {
	return xxx_messageInfo_YrTotalResponse.Size(m)
}
func (m *YrTotalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_YrTotalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_YrTotalResponse proto.InternalMessageInfo

func (m *YrTotalResponse) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *YrTotalResponse) GetYearlyTotal() *YrTotalResult {
	if m != nil {
		return m.YearlyTotal
	}
	return nil
}

func (m *YrTotalResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *YrTotalResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type YrTotalResult struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Year                 string   `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Party                string   `protobuf:"bytes,4,opt,name=Party,proto3" json:"Party,omitempty"`
	Total                float32  `protobuf:"fixed32,5,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YrTotalResult) Reset()         { *m = YrTotalResult{} }
func (m *YrTotalResult) String() string { return proto.CompactTextString(m) }
func (*YrTotalResult) ProtoMessage()    {}
func (*YrTotalResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{9}
}

func (m *YrTotalResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YrTotalResult.Unmarshal(m, b)
}
func (m *YrTotalResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YrTotalResult.Marshal(b, m, deterministic)
}
func (m *YrTotalResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YrTotalResult.Merge(m, src)
}
func (m *YrTotalResult) XXX_Size() int {
	return xxx_messageInfo_YrTotalResult.Size(m)
}
func (m *YrTotalResult) XXX_DiscardUnknown() {
	xxx_messageInfo_YrTotalResult.DiscardUnknown(m)
}

var xxx_messageInfo_YrTotalResult proto.InternalMessageInfo

func (m *YrTotalResult) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *YrTotalResult) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *YrTotalResult) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *YrTotalResult) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *YrTotalResult) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type GetObjRequest struct {
	UID                  string               `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	ObjectID             string               `protobuf:"bytes,2,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Bucket               string               `protobuf:"bytes,3,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Years                []string             `protobuf:"bytes,4,rep,name=Years,proto3" json:"Years,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Msg                  string               `protobuf:"bytes,6,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetObjRequest) Reset()         { *m = GetObjRequest{} }
func (m *GetObjRequest) String() string { return proto.CompactTextString(m) }
func (*GetObjRequest) ProtoMessage()    {}
func (*GetObjRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{10}
}

func (m *GetObjRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjRequest.Unmarshal(m, b)
}
func (m *GetObjRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjRequest.Marshal(b, m, deterministic)
}
func (m *GetObjRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjRequest.Merge(m, src)
}
func (m *GetObjRequest) XXX_Size() int {
	return xxx_messageInfo_GetObjRequest.Size(m)
}
func (m *GetObjRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjRequest proto.InternalMessageInfo

func (m *GetObjRequest) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *GetObjRequest) GetObjectID() string {
	if m != nil {
		return m.ObjectID
	}
	return ""
}

func (m *GetObjRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetObjRequest) GetYears() []string {
	if m != nil {
		return m.Years
	}
	return nil
}

func (m *GetObjRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GetObjRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetObjResponse struct {
	UID      string `protobuf:"bytes,1,opt,name=UID,proto3" json:"UID,omitempty"`
	ObjectID string `protobuf:"bytes,2,opt,name=ObjectID,proto3" json:"ObjectID,omitempty"`
	Bucket   string `protobuf:"bytes,3,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	// datasets for each year in request aggregated
	// into singular object encoded on server prior
	// to encoding response
	Object               []byte               `protobuf:"bytes,4,opt,name=Object,proto3" json:"Object,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Msg                  string               `protobuf:"bytes,6,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetObjResponse) Reset()         { *m = GetObjResponse{} }
func (m *GetObjResponse) String() string { return proto.CompactTextString(m) }
func (*GetObjResponse) ProtoMessage()    {}
func (*GetObjResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{11}
}

func (m *GetObjResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjResponse.Unmarshal(m, b)
}
func (m *GetObjResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjResponse.Marshal(b, m, deterministic)
}
func (m *GetObjResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjResponse.Merge(m, src)
}
func (m *GetObjResponse) XXX_Size() int {
	return xxx_messageInfo_GetObjResponse.Size(m)
}
func (m *GetObjResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjResponse proto.InternalMessageInfo

func (m *GetObjResponse) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *GetObjResponse) GetObjectID() string {
	if m != nil {
		return m.ObjectID
	}
	return ""
}

func (m *GetObjResponse) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetObjResponse) GetObject() []byte {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *GetObjResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GetObjResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*SearchRequest)(nil), "proto.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "proto.SearchResponse")
	proto.RegisterType((*SearchResult)(nil), "proto.SearchResult")
	proto.RegisterType((*RankingsRequest)(nil), "proto.RankingsRequest")
	proto.RegisterType((*RankingsResponse)(nil), "proto.RankingsResponse")
	proto.RegisterType((*RankingsResult)(nil), "proto.RankingsResult")
	proto.RegisterMapType((map[string]float32)(nil), "proto.RankingsResult.RankingsListEntry")
	proto.RegisterType((*YrTotalRequest)(nil), "proto.YrTotalRequest")
	proto.RegisterType((*YrTotalResponse)(nil), "proto.YrTotalResponse")
	proto.RegisterType((*YrTotalResult)(nil), "proto.YrTotalResult")
	proto.RegisterType((*GetObjRequest)(nil), "proto.GetObjRequest")
	proto.RegisterType((*GetObjResponse)(nil), "proto.GetObjResponse")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xed, 0x38, 0x71, 0x9a, 0xde, 0xa4, 0x69, 0xbf, 0xf9, 0xda, 0x60, 0x79, 0x43, 0xe4, 0x0d,
	0xdd, 0x90, 0x8a, 0x20, 0xa1, 0x0a, 0x90, 0x2a, 0x68, 0x2b, 0x54, 0x41, 0x5b, 0x70, 0x0b, 0x52,
	0x97, 0x4e, 0x35, 0x98, 0x34, 0x4e, 0x1c, 0x3c, 0xe3, 0x82, 0xc5, 0x8a, 0x3d, 0xaf, 0xc0, 0x8a,
	0x05, 0x62, 0x8f, 0x84, 0xc4, 0x3b, 0xf0, 0x4e, 0x68, 0xfe, 0xfc, 0xd3, 0xd4, 0x88, 0xb6, 0x61,
	0x95, 0xb9, 0xa3, 0x33, 0xf7, 0x9e, 0x7b, 0xcf, 0xf1, 0x4c, 0xa0, 0x49, 0x49, 0x74, 0x46, 0xa2,
	0xee, 0x24, 0x0a, 0x59, 0x88, 0x4d, 0xf1, 0x63, 0xdf, 0xf4, 0xc3, 0xd0, 0x0f, 0xc8, 0xba, 0x88,
	0xfa, 0xf1, 0xeb, 0x75, 0x36, 0x18, 0x11, 0xca, 0xbc, 0xd1, 0x44, 0xe2, 0x9c, 0x79, 0x30, 0x77,
	0x46, 0x13, 0x96, 0x38, 0x1f, 0x11, 0x2c, 0x1e, 0x12, 0x2f, 0x3a, 0x79, 0xe3, 0x92, 0xb7, 0x31,
	0xa1, 0x0c, 0x2f, 0x43, 0xe5, 0xe5, 0xee, 0xb6, 0x85, 0x3a, 0x68, 0x6d, 0xc1, 0xe5, 0x4b, 0x8c,
	0xa1, 0x7a, 0x44, 0xde, 0x33, 0xcb, 0x10, 0x5b, 0x62, 0x8d, 0x37, 0x60, 0xe1, 0x48, 0xe7, 0xb4,
	0x2a, 0x1d, 0xb4, 0xd6, 0xe8, 0xd9, 0x5d, 0x59, 0xb5, 0xab, 0xab, 0x76, 0x53, 0x84, 0x9b, 0x81,
	0x79, 0xfe, 0x3d, 0xea, 0x5b, 0x55, 0x99, 0x7f, 0x8f, 0xfa, 0xce, 0x67, 0x04, 0x2d, 0xcd, 0x81,
	0x4e, 0xc2, 0x31, 0x25, 0x17, 0x90, 0xb8, 0x0d, 0xf3, 0x2e, 0xa1, 0x71, 0xc0, 0xa8, 0x65, 0x74,
	0x2a, 0x6b, 0x8d, 0xde, 0xff, 0xb2, 0x4e, 0x37, 0x3d, 0x19, 0x07, 0xcc, 0xd5, 0x98, 0x99, 0xf2,
	0x8b, 0xa0, 0x99, 0x2f, 0x82, 0x5b, 0x60, 0xa4, 0xdc, 0x0c, 0x39, 0x9f, 0x7d, 0x6f, 0x44, 0xf4,
	0x7c, 0xf8, 0x9a, 0xef, 0x6d, 0x0d, 0x58, 0x22, 0x4a, 0x2f, 0xb8, 0x62, 0x8d, 0x57, 0xc0, 0x3c,
	0x64, 0x1e, 0x23, 0x2a, 0xb7, 0x0c, 0xf8, 0xee, 0x31, 0xf1, 0x22, 0x6a, 0x99, 0x9d, 0x0a, 0xdf,
	0x15, 0x81, 0xf3, 0x0b, 0xc1, 0x92, 0xeb, 0x8d, 0x87, 0x83, 0xb1, 0x4f, 0xff, 0xa8, 0x0c, 0x87,
	0xeb, 0xca, 0x7c, 0x8d, 0xdb, 0x50, 0x7b, 0x1c, 0x9f, 0x0c, 0x09, 0x53, 0xb5, 0x55, 0x84, 0x6d,
	0xa8, 0x6f, 0x79, 0x8c, 0xf8, 0x61, 0x94, 0x28, 0x02, 0x69, 0xcc, 0x39, 0x3c, 0xf7, 0x22, 0x96,
	0x58, 0xa6, 0x64, 0x26, 0x82, 0xe2, 0x0c, 0x6b, 0x57, 0x98, 0xe1, 0x7c, 0x36, 0xc3, 0x2f, 0x08,
	0x96, 0xb3, 0x7e, 0x4a, 0x55, 0xbe, 0x03, 0x75, 0x8d, 0x12, 0x4d, 0x35, 0x7a, 0xab, 0x4a, 0xe6,
	0xdc, 0x61, 0x2e, 0x74, 0x0a, 0xbb, 0xbe, 0xd2, 0xf5, 0x8c, 0xe5, 0x27, 0x03, 0x5a, 0xc5, 0x42,
	0x17, 0x89, 0xfd, 0x0f, 0x47, 0xfe, 0x14, 0x9a, 0xba, 0xfe, 0xb3, 0x01, 0x65, 0x56, 0x4d, 0x58,
	0xfd, 0xd6, 0x85, 0x33, 0xe8, 0xe6, 0x91, 0x3b, 0x63, 0x16, 0x25, 0x6e, 0xe1, 0xb0, 0xbd, 0x09,
	0xff, 0x4d, 0x41, 0x78, 0xd3, 0x43, 0x92, 0xe8, 0x99, 0x0f, 0x89, 0x60, 0x72, 0xe6, 0x05, 0xb1,
	0xf4, 0xaf, 0xe1, 0xca, 0xe0, 0xbe, 0xb1, 0x81, 0x9c, 0xef, 0x08, 0x5a, 0xc7, 0xd1, 0x51, 0xc8,
	0xbc, 0xe0, 0x72, 0x1e, 0xcc, 0x37, 0x5e, 0x29, 0x6b, 0xbc, 0x5a, 0xea, 0x35, 0xf3, 0x0a, 0x2a,
	0xd6, 0x32, 0x15, 0xbf, 0x22, 0x58, 0x4a, 0x69, 0x97, 0x5a, 0xed, 0x1e, 0x34, 0x38, 0xd7, 0x20,
	0x11, 0x40, 0xe5, 0xb6, 0x15, 0x35, 0xe9, 0xec, 0x38, 0x37, 0x5b, 0x1e, 0x78, 0x7d, 0xbf, 0xe5,
	0xbe, 0x8a, 0x0f, 0xb0, 0x58, 0xa8, 0xf4, 0x57, 0x6e, 0xbb, 0xfc, 0x70, 0x57, 0xc0, 0x94, 0x4d,
	0x9a, 0x52, 0x61, 0x11, 0x38, 0x3f, 0x10, 0x2c, 0x3e, 0x21, 0xec, 0xa0, 0x7f, 0x5a, 0x2e, 0xae,
	0x0d, 0xf5, 0x83, 0xfe, 0x29, 0x39, 0x61, 0xbb, 0xdb, 0x8a, 0x43, 0x1a, 0x97, 0xba, 0x3e, 0xbd,
	0xd0, 0xaa, 0xb9, 0x0b, 0x6d, 0xa6, 0x02, 0xff, 0x44, 0xd0, 0xd2, 0xcc, 0x4b, 0xf5, 0xbd, 0x0a,
	0xf5, 0x36, 0xd4, 0x24, 0x46, 0xcc, 0xaf, 0xe9, 0xaa, 0x68, 0x96, 0xe4, 0x7b, 0xdf, 0x0c, 0xa8,
	0xbe, 0x1a, 0x90, 0x77, 0xf8, 0x21, 0x34, 0xe4, 0xb3, 0xf2, 0x22, 0x26, 0x5c, 0xba, 0x73, 0xef,
	0x99, 0x90, 0xc4, 0x5e, 0x3d, 0xff, 0xca, 0x89, 0x76, 0x9d, 0x39, 0xfc, 0x08, 0x9a, 0x3c, 0x4b,
	0x7a, 0x0d, 0xb6, 0xa7, 0xee, 0x08, 0x99, 0xe0, 0xc6, 0xf4, 0xdd, 0xa1, 0x53, 0x6c, 0xca, 0x14,
	0xca, 0x81, 0x14, 0xaf, 0x9e, 0x37, 0xbf, 0xcc, 0xd0, 0x9e, 0xfa, 0x26, 0x74, 0x82, 0x07, 0x00,
	0x3c, 0x81, 0x1a, 0x92, 0x6e, 0xa0, 0xe0, 0xa9, 0xb4, 0x81, 0xa2, 0x5e, 0xce, 0x1c, 0x76, 0xa0,
	0xba, 0x1f, 0x1e, 0x4c, 0x70, 0x53, 0x01, 0xc4, 0xff, 0x11, 0xbb, 0x10, 0xf5, 0x6b, 0x22, 0xb8,
	0xfb, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x60, 0xe7, 0x33, 0x24, 0xe5, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ViewClient is the client API for View service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ViewClient interface {
	// take user-input search query and return a list of matching results
	SearchQuery(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// retrieve rankings list matching specified criteria
	ViewRankings(ctx context.Context, in *RankingsRequest, opts ...grpc.CallOption) (*RankingsResponse, error)
	// retrieve yearly total matching specified criteria
	ViewYrTotals(ctx context.Context, in *YrTotalRequest, opts ...grpc.CallOption) (*YrTotalResponse, error)
	// retrieve object from cache/DynamoDB
	ViewObject(ctx context.Context, in *GetObjRequest, opts ...grpc.CallOption) (*GetObjResponse, error)
	// One empty request, ZERO processing, followed by one empty response
	// (minimum effort to do message serialization).
	NoOp(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type viewClient struct {
	cc grpc.ClientConnInterface
}

func NewViewClient(cc grpc.ClientConnInterface) ViewClient {
	return &viewClient{cc}
}

func (c *viewClient) SearchQuery(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/proto.View/SearchQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) ViewRankings(ctx context.Context, in *RankingsRequest, opts ...grpc.CallOption) (*RankingsResponse, error) {
	out := new(RankingsResponse)
	err := c.cc.Invoke(ctx, "/proto.View/ViewRankings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) ViewYrTotals(ctx context.Context, in *YrTotalRequest, opts ...grpc.CallOption) (*YrTotalResponse, error) {
	out := new(YrTotalResponse)
	err := c.cc.Invoke(ctx, "/proto.View/ViewYrTotals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) ViewObject(ctx context.Context, in *GetObjRequest, opts ...grpc.CallOption) (*GetObjResponse, error) {
	out := new(GetObjResponse)
	err := c.cc.Invoke(ctx, "/proto.View/ViewObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *viewClient) NoOp(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.View/NoOp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ViewServer is the server API for View service.
type ViewServer interface {
	// take user-input search query and return a list of matching results
	SearchQuery(context.Context, *SearchRequest) (*SearchResponse, error)
	// retrieve rankings list matching specified criteria
	ViewRankings(context.Context, *RankingsRequest) (*RankingsResponse, error)
	// retrieve yearly total matching specified criteria
	ViewYrTotals(context.Context, *YrTotalRequest) (*YrTotalResponse, error)
	// retrieve object from cache/DynamoDB
	ViewObject(context.Context, *GetObjRequest) (*GetObjResponse, error)
	// One empty request, ZERO processing, followed by one empty response
	// (minimum effort to do message serialization).
	NoOp(context.Context, *Empty) (*Empty, error)
}

// UnimplementedViewServer can be embedded to have forward compatible implementations.
type UnimplementedViewServer struct {
}

func (*UnimplementedViewServer) SearchQuery(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchQuery not implemented")
}
func (*UnimplementedViewServer) ViewRankings(ctx context.Context, req *RankingsRequest) (*RankingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewRankings not implemented")
}
func (*UnimplementedViewServer) ViewYrTotals(ctx context.Context, req *YrTotalRequest) (*YrTotalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewYrTotals not implemented")
}
func (*UnimplementedViewServer) ViewObject(ctx context.Context, req *GetObjRequest) (*GetObjResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewObject not implemented")
}
func (*UnimplementedViewServer) NoOp(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoOp not implemented")
}

func RegisterViewServer(s *grpc.Server, srv ViewServer) {
	s.RegisterService(&_View_serviceDesc, srv)
}

func _View_SearchQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).SearchQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.View/SearchQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).SearchQuery(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_ViewRankings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).ViewRankings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.View/ViewRankings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).ViewRankings(ctx, req.(*RankingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_ViewYrTotals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YrTotalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).ViewYrTotals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.View/ViewYrTotals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).ViewYrTotals(ctx, req.(*YrTotalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_ViewObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).ViewObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.View/ViewObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).ViewObject(ctx, req.(*GetObjRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _View_NoOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViewServer).NoOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.View/NoOp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViewServer).NoOp(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _View_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.View",
	HandlerType: (*ViewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchQuery",
			Handler:    _View_SearchQuery_Handler,
		},
		{
			MethodName: "ViewRankings",
			Handler:    _View_ViewRankings_Handler,
		},
		{
			MethodName: "ViewYrTotals",
			Handler:    _View_ViewYrTotals_Handler,
		},
		{
			MethodName: "ViewObject",
			Handler:    _View_ViewObject_Handler,
		},
		{
			MethodName: "NoOp",
			Handler:    _View_NoOp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
