// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package network

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeProto struct {
	ID                   string                         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string                         `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 string                         `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	WeightedEdges        map[string]*NodeProto_InnerMap `protobuf:"bytes,5,rep,name=WeightedEdges,proto3" json:"WeightedEdges,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *NodeProto) Reset()         { *m = NodeProto{} }
func (m *NodeProto) String() string { return proto.CompactTextString(m) }
func (*NodeProto) ProtoMessage()    {}
func (*NodeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *NodeProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeProto.Unmarshal(m, b)
}
func (m *NodeProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeProto.Marshal(b, m, deterministic)
}
func (m *NodeProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeProto.Merge(m, src)
}
func (m *NodeProto) XXX_Size() int {
	return xxx_messageInfo_NodeProto.Size(m)
}
func (m *NodeProto) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeProto.DiscardUnknown(m)
}

var xxx_messageInfo_NodeProto proto.InternalMessageInfo

func (m *NodeProto) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NodeProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeProto) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NodeProto) GetWeightedEdges() map[string]*NodeProto_InnerMap {
	if m != nil {
		return m.WeightedEdges
	}
	return nil
}

type NodeProto_InnerMap struct {
	Weights              map[string]float32 `protobuf:"bytes,1,rep,name=Weights,proto3" json:"Weights,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NodeProto_InnerMap) Reset()         { *m = NodeProto_InnerMap{} }
func (m *NodeProto_InnerMap) String() string { return proto.CompactTextString(m) }
func (*NodeProto_InnerMap) ProtoMessage()    {}
func (*NodeProto_InnerMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0, 0}
}

func (m *NodeProto_InnerMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeProto_InnerMap.Unmarshal(m, b)
}
func (m *NodeProto_InnerMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeProto_InnerMap.Marshal(b, m, deterministic)
}
func (m *NodeProto_InnerMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeProto_InnerMap.Merge(m, src)
}
func (m *NodeProto_InnerMap) XXX_Size() int {
	return xxx_messageInfo_NodeProto_InnerMap.Size(m)
}
func (m *NodeProto_InnerMap) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeProto_InnerMap.DiscardUnknown(m)
}

var xxx_messageInfo_NodeProto_InnerMap proto.InternalMessageInfo

func (m *NodeProto_InnerMap) GetWeights() map[string]float32 {
	if m != nil {
		return m.Weights
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeProto)(nil), "network.NodeProto")
	proto.RegisterMapType((map[string]*NodeProto_InnerMap)(nil), "network.NodeProto.WeightedEdgesEntry")
	proto.RegisterType((*NodeProto_InnerMap)(nil), "network.NodeProto.InnerMap")
	proto.RegisterMapType((map[string]float32)(nil), "network.NodeProto.InnerMap.WeightsEntry")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcb, 0x4f, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0x56,
	0xfa, 0xc3, 0xc4, 0xc5, 0xe9, 0x97, 0x9f, 0x92, 0x1a, 0x00, 0x16, 0xe6, 0xe3, 0x62, 0xf2, 0x74,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xf2, 0x74, 0x11, 0x12, 0xe2, 0x62, 0xf1, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x02, 0x8b, 0x80, 0xd9, 0x20, 0xb1, 0x90, 0xca, 0x82, 0x54, 0x09, 0x66,
	0x88, 0x18, 0x88, 0x2d, 0xe4, 0xcd, 0xc5, 0x1b, 0x9e, 0x9a, 0x99, 0x9e, 0x51, 0x92, 0x9a, 0xe2,
	0x9a, 0x92, 0x9e, 0x5a, 0x2c, 0xc1, 0xaa, 0xc0, 0xac, 0xc1, 0x6d, 0xa4, 0xaa, 0x07, 0xb5, 0x46,
	0x0f, 0x6e, 0x85, 0x1e, 0x8a, 0x3a, 0xd7, 0xbc, 0x92, 0xa2, 0xca, 0x20, 0x54, 0xbd, 0x52, 0x5d,
	0x8c, 0x5c, 0x1c, 0x9e, 0x79, 0x79, 0xa9, 0x45, 0xbe, 0x89, 0x05, 0x42, 0x4e, 0x5c, 0xec, 0x10,
	0xd9, 0x62, 0x09, 0x46, 0xb0, 0x99, 0x1a, 0x58, 0xcc, 0x84, 0xa9, 0x86, 0x1a, 0x0e, 0x35, 0x16,
	0xa6, 0x51, 0xca, 0x8a, 0x8b, 0x07, 0x59, 0x42, 0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x12, 0xea,
	0x4d, 0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x14, 0xe2, 0x51, 0xa6, 0x20, 0x08,
	0xc7, 0x8a, 0xc9, 0x82, 0x51, 0x2a, 0x96, 0x4b, 0x08, 0xd3, 0xc5, 0x58, 0x4c, 0x30, 0x44, 0x36,
	0x81, 0xdb, 0x48, 0x1a, 0x8f, 0x2b, 0x91, 0x8c, 0x4f, 0x62, 0x03, 0x47, 0x87, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x0d, 0xda, 0x42, 0x9f, 0x9c, 0x01, 0x00, 0x00,
}
